/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSArray;

@interface _ORKTableSection : NSObject {

	BOOL _hasChoiceRows;
	NSString* _title;
	NSArray* _items;

}

@property (nonatomic,copy) NSString * title;                      //@synthesize title=_title - In the implementation block
@property (nonatomic,copy,readonly) NSArray * items;              //@synthesize items=_items - In the implementation block
@property (nonatomic,readonly) BOOL hasChoiceRows;                //@synthesize hasChoiceRows=_hasChoiceRows - In the implementation block
@property (nonatomic,readonly) double maxLabelWidth; 
-(double)maxLabelWidth;
-(void)addFormItem:(id)arg1 ;
-(BOOL)hasChoiceRows;
-(id)init;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)title;
-(NSArray *)items;
@end

