/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:12 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKActiveStepViewController.h>
#import <ResearchKit/_ORKSpatialSpanMemoryGameViewDelegate.h>

@class _ORKSpatialSpanMemoryContentView, _ORKState, NSDictionary, _ORKSpatialSpanGameState, NSMutableArray, NSTimer, NSString;

@interface _ORKSpatialSpanMemoryStepViewController : ORKActiveStepViewController <_ORKSpatialSpanMemoryGameViewDelegate> {

	_ORKSpatialSpanMemoryContentView* _contentView;
	_ORKState* _state;
	NSDictionary* _states;
	ORKGridSize _gridSize;
	_ORKSpatialSpanGameState* _currentGameState;
	NSMutableArray* _gameRecords;
	double _gameStartTime;
	long long _lastRoundScore;
	long long _playbackIndex;
	long long _score;
	long long _numberOfItems;
	long long _gamesCounter;
	long long _consecutiveGamesFailed;
	long long _nextGameSequenceLength;
	NSTimer* _playbackTimer;
	NSTimer* _activityTimer;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithStep:(id)arg1 ;
-(void)_stepDidChange;
-(void)_resetUI;
-(void)_handleUserTap:(id)arg1 ;
-(void)_initializeStates;
-(id)_currentGameRecord;
-(void)_updateGameRecordOnTouch:(long long)arg1 location:(CGPoint)arg2 ;
-(id)spatialSpanStep;
-(void)_resetForNewGame;
-(ORKGridSize)_gridSizeForSpan:(long long)arg1 ;
-(void)_createGameRecord;
-(void)_applyTargetState:(long long)arg1 toSequenceIndex:(long long)arg2 duration:(double)arg3 ;
-(void)_playbackNextItem;
-(void)_updateGameRecordScore;
-(void)_activityTimeout;
-(void)_setNumberOfItems:(long long)arg1 ;
-(void)_updateGameRecordTargetRects;
-(void)_resetActivityTimer;
-(void)_updateGameRecordOnStartingGamePlay;
-(void)_setScore:(long long)arg1 ;
-(void)_updateGameRecordOnSuccess;
-(void)_updateGameCountersForSuccess:(BOOL)arg1 ;
-(BOOL)_finishIfCompletedGames;
-(void)_continueAction;
-(void)_updateGameRecordOnFailure;
-(void)_tryAgainAction;
-(void)_updateGameRecordOnTimeout;
-(void)_updateGameRecordOnPause;
-(void)_resetGameAndUI;
-(void)_startPlayback;
-(void)_finishPlayback;
-(void)_startGameplay;
-(void)_finishGameplay;
-(void)_showSuccess;
-(void)_showFailed;
-(void)_showTimeout;
-(void)_doRestart;
-(void)_showComplete;
-(void)_showPausedFromState:(id)arg1 ;
-(void)gameView:(id)arg1 didTapTileWithIndex:(long long)arg2 recognizer:(id)arg3 ;
-(void)_transitionToState:(long long)arg1 ;
-(void)suspend;
-(void)viewDidLoad;
-(void)start;
-(void)resume;
-(id)result;
-(void)finish;
@end

