/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKActiveStepCustomView.h>

@class CAShapeLayer, ORKSubheadlineLabel, _ORKCountDownViewLabel, UIView;

@interface _ORKCountdownView : ORKActiveStepCustomView {

	CAShapeLayer* _circleLayer;
	ORKSubheadlineLabel* _textLabel;
	_ORKCountDownViewLabel* _timeLabel;
	UIView* _progressView;

}

@property (nonatomic,retain) ORKSubheadlineLabel * textLabel;                 //@synthesize textLabel=_textLabel - In the implementation block
@property (nonatomic,retain) _ORKCountDownViewLabel * timeLabel;              //@synthesize timeLabel=_timeLabel - In the implementation block
@property (nonatomic,retain) UIView * progressView;                           //@synthesize progressView=_progressView - In the implementation block
-(void)startAnimateWithDuration:(double)arg1 ;
-(id)init;
-(void)tintColorDidChange;
-(id)accessibilityLabel;
-(ORKSubheadlineLabel *)textLabel;
-(void)setProgressView:(UIView *)arg1 ;
-(UIView *)progressView;
-(unsigned long long)accessibilityTraits;
-(BOOL)isAccessibilityElement;
-(void)setTextLabel:(ORKSubheadlineLabel *)arg1 ;
-(void)setTimeLabel:(_ORKCountDownViewLabel *)arg1 ;
-(_ORKCountDownViewLabel *)timeLabel;
@end

