/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKActiveStepCustomView.h>

@class NSArray, NSMutableArray, UIColor, ORKHeadlineLabel, UILabel, _ORKAudioGraphView;

@interface _ORKAudioContentView : ORKActiveStepCustomView {

	NSArray* _constraints;
	NSMutableArray* _samples;
	UIColor* _keyColor;
	BOOL _finished;
	UIColor* _alertColor;
	double _timeLeft;
	double _alertThreshold;
	ORKHeadlineLabel* _alertLabel;
	UILabel* _timerLabel;
	_ORKAudioGraphView* _graphView;

}

@property (nonatomic,copy) UIColor * keyColor; 
@property (nonatomic,copy) UIColor * alertColor;                           //@synthesize alertColor=_alertColor - In the implementation block
@property (assign,getter=isFinished,nonatomic) BOOL finished;              //@synthesize finished=_finished - In the implementation block
@property (assign,nonatomic) double timeLeft;                              //@synthesize timeLeft=_timeLeft - In the implementation block
@property (assign,nonatomic) double alertThreshold;                        //@synthesize alertThreshold=_alertThreshold - In the implementation block
@property (nonatomic,copy) NSArray * samples;                              //@synthesize samples=_samples - In the implementation block
@property (nonatomic,retain) ORKHeadlineLabel * alertLabel;                //@synthesize alertLabel=_alertLabel - In the implementation block
@property (nonatomic,retain) UILabel * timerLabel;                         //@synthesize timerLabel=_timerLabel - In the implementation block
@property (nonatomic,retain) _ORKAudioGraphView * graphView;               //@synthesize graphView=_graphView - In the implementation block
-(void)setTimeLeft:(double)arg1 ;
-(void)_updateTimerLabel;
-(double)timeLeft;
-(void)addSample:(id)arg1 ;
-(void)setKeyColor:(UIColor *)arg1 ;
-(void)setAlertColor:(UIColor *)arg1 ;
-(void)setAlertThreshold:(double)arg1 ;
-(UIColor *)keyColor;
-(UIColor *)alertColor;
-(double)alertThreshold;
-(void)setAlertLabel:(ORKHeadlineLabel *)arg1 ;
-(void)setTimerLabel:(UILabel *)arg1 ;
-(void)setGraphView:(_ORKAudioGraphView *)arg1 ;
-(void)_updateGraphSamples;
-(void)_applyKeyColor;
-(void)_updateAlertLabelHidden;
-(void)removeAllSamples;
-(ORKHeadlineLabel *)alertLabel;
-(UILabel *)timerLabel;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)tintColorDidChange;
-(id)accessibilityLabel;
-(void)updateConstraints;
-(unsigned long long)accessibilityTraits;
-(BOOL)isAccessibilityElement;
-(BOOL)isFinished;
-(void)setFinished:(BOOL)arg1 ;
-(NSArray *)samples;
-(void)setSamples:(NSArray *)arg1 ;
-(_ORKAudioGraphView *)graphView;
@end

