/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableArray, _ORKSpatialSpanGame;

@interface _ORKSpatialSpanGameState : NSObject {

	NSMutableArray* _plays;
	long long* _states;
	BOOL _complete;
	_ORKSpatialSpanGame* _game;

}

@property (nonatomic,readonly) _ORKSpatialSpanGame * game;                   //@synthesize game=_game - In the implementation block
@property (getter=isComplete,nonatomic,readonly) BOOL complete;              //@synthesize complete=_complete - In the implementation block
-(long long)playTileIndex:(long long)arg1 ;
-(long long)currentStepIndex;
-(void)enumerateTilesWithHandler:(/*^block*/id)arg1 ;
-(long long)lastSuccessfulTileIndex;
-(BOOL)isComplete;
-(void)dealloc;
-(void)reset;
-(_ORKSpatialSpanGame *)game;
-(id)initWithGame:(id)arg1 ;
@end

