/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <UIKit/UIView.h>

@class UIView, NSArray, _ORKActiveStepQuantityView;

@interface _ORKQuantityPairView : UIView {

	UIView* _metricKeyline;
	NSArray* _constraints;
	BOOL _keylineHidden;
	_ORKActiveStepQuantityView* _leftView;
	_ORKActiveStepQuantityView* _rightView;

}

@property (nonatomic,retain) _ORKActiveStepQuantityView * leftView;               //@synthesize leftView=_leftView - In the implementation block
@property (nonatomic,retain) _ORKActiveStepQuantityView * rightView;              //@synthesize rightView=_rightView - In the implementation block
@property (assign,nonatomic) BOOL keylineHidden;                                  //@synthesize keylineHidden=_keylineHidden - In the implementation block
-(void)setKeylineHidden:(BOOL)arg1 ;
-(BOOL)keylineHidden;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)updateConstraints;
-(void)setLeftView:(_ORKActiveStepQuantityView *)arg1 ;
-(void)setRightView:(_ORKActiveStepQuantityView *)arg1 ;
-(_ORKActiveStepQuantityView *)leftView;
-(_ORKActiveStepQuantityView *)rightView;
@end

