/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <UIKit/UIView.h>

@class UIColor, NSArray;

@interface _ORKAudioGraphView : UIView {

	UIColor* _keyColor;
	UIColor* _alertColor;
	NSArray* _values;
	double _alertThreshold;

}

@property (nonatomic,retain) UIColor * keyColor;                 //@synthesize keyColor=_keyColor - In the implementation block
@property (nonatomic,retain) UIColor * alertColor;               //@synthesize alertColor=_alertColor - In the implementation block
@property (nonatomic,copy) NSArray * values;                     //@synthesize values=_values - In the implementation block
@property (assign,nonatomic) double alertThreshold;              //@synthesize alertThreshold=_alertThreshold - In the implementation block
-(void)setKeyColor:(UIColor *)arg1 ;
-(void)setAlertColor:(UIColor *)arg1 ;
-(void)setAlertThreshold:(double)arg1 ;
-(UIColor *)keyColor;
-(UIColor *)alertColor;
-(double)alertThreshold;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(void)setValues:(NSArray *)arg1 ;
-(NSArray *)values;
@end

