/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKActiveStepCustomView.h>

@class _ORKQuantityLabel, _ORKQuantityPairView, UIView, _ORKTintedImageView, NSLengthFormatter, NSLayoutConstraint, NSArray, NSString, UIImage;

@interface _ORKFitnessContentView : ORKActiveStepCustomView {

	_ORKQuantityLabel* _timerLabel;
	_ORKQuantityPairView* _quantityPairView;
	UIView* _imageSpacer1;
	UIView* _imageSpacer2;
	_ORKTintedImageView* _imageView;
	NSLengthFormatter* _lengthFormatter;
	NSLayoutConstraint* _imageRatioConstraint;
	long long _screenType;
	NSArray* _constraints;
	NSLayoutConstraint* _topConstraint;
	BOOL _finished;
	BOOL _hasHeartRate;
	BOOL _hasDistance;
	NSString* _heartRate;
	double _distanceInMeters;
	UIImage* _image;
	double _timeLeft;

}

@property (assign,getter=isFinished,nonatomic) BOOL finished;              //@synthesize finished=_finished - In the implementation block
@property (assign,nonatomic) BOOL hasHeartRate;                            //@synthesize hasHeartRate=_hasHeartRate - In the implementation block
@property (assign,nonatomic) BOOL hasDistance;                             //@synthesize hasDistance=_hasDistance - In the implementation block
@property (nonatomic,copy) NSString * heartRate;                           //@synthesize heartRate=_heartRate - In the implementation block
@property (assign,nonatomic) double distanceInMeters;                      //@synthesize distanceInMeters=_distanceInMeters - In the implementation block
@property (nonatomic,retain) UIImage * image;                              //@synthesize image=_image - In the implementation block
@property (assign,nonatomic) double timeLeft;                              //@synthesize timeLeft=_timeLeft - In the implementation block
-(void)setTimeLeft:(double)arg1 ;
-(void)setHasHeartRate:(BOOL)arg1 ;
-(void)setHeartRate:(NSString *)arg1 ;
-(void)updateConstraintConstants;
-(id)_heartRateView;
-(void)_updateKeylineVisible;
-(id)_distanceView;
-(void)_updateTimerLabel;
-(BOOL)hasHeartRate;
-(NSString *)heartRate;
-(double)distanceInMeters;
-(double)timeLeft;
-(void)setDistanceInMeters:(double)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setImage:(UIImage *)arg1 ;
-(UIImage *)image;
-(void)willMoveToWindow:(id)arg1 ;
-(void)updateConstraints;
-(BOOL)isFinished;
-(void)setFinished:(BOOL)arg1 ;
-(void)setHasDistance:(BOOL)arg1 ;
-(BOOL)hasDistance;
@end

