/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/_ORKFormItemCell.h>
#import <UIKit/UITextViewDelegate.h>

@class ORKFormTextView, NSString;

@interface _ORKFormItemTextCell : _ORKFormItemCell <UITextViewDelegate> {

	ORKFormTextView* _textView;
	double _lastSeenLineCount;
	long long _maxLength;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setFormItem:(id)arg1 ;
-(void)_cellInit;
-(void)_answerDidChange;
-(void)_inputValueDidChange;
-(void)_applyAnswerFormat;
-(BOOL)resignFirstResponder;
-(BOOL)becomeFirstResponder;
-(void)textViewDidBeginEditing:(id)arg1 ;
-(void)textViewDidEndEditing:(id)arg1 ;
-(BOOL)textView:(id)arg1 shouldChangeTextInRange:(NSRange)arg2 replacementText:(id)arg3 ;
-(void)textViewDidChange:(id)arg1 ;
-(id)_placeholderColor;
@end

