/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class ORKFormItem, ORKAnswerFormat, ORKTextChoice, ORKTextChoiceAnswerFormat, ORKBooleanAnswerFormat;

@interface _ORKTableCellItem : NSObject {

	BOOL _singleChoice;
	ORKFormItem* _formItem;
	ORKAnswerFormat* _answerFormat;
	ORKTextChoice* _choice;
	unsigned long long _choiceIndex;

}

@property (nonatomic,copy) ORKFormItem * formItem;                                              //@synthesize formItem=_formItem - In the implementation block
@property (nonatomic,copy) ORKAnswerFormat * answerFormat;                                      //@synthesize answerFormat=_answerFormat - In the implementation block
@property (nonatomic,readonly) double labelWidth; 
@property (nonatomic,readonly) ORKTextChoiceAnswerFormat * textChoiceAnswerFormat; 
@property (nonatomic,readonly) ORKBooleanAnswerFormat * booleanAnswerFormat; 
@property (nonatomic,readonly) BOOL singleChoice;                                               //@synthesize singleChoice=_singleChoice - In the implementation block
@property (nonatomic,copy,readonly) ORKTextChoice * choice;                                     //@synthesize choice=_choice - In the implementation block
@property (nonatomic,readonly) unsigned long long choiceIndex;                                  //@synthesize choiceIndex=_choiceIndex - In the implementation block
-(ORKAnswerFormat *)answerFormat;
-(void)setFormItem:(ORKFormItem *)arg1 ;
-(ORKFormItem *)formItem;
-(ORKTextChoiceAnswerFormat *)textChoiceAnswerFormat;
-(ORKBooleanAnswerFormat *)booleanAnswerFormat;
-(id)initWithFormItem:(id)arg1 ;
-(id)initWithFormItem:(id)arg1 choiceIndex:(unsigned long long)arg2 ;
-(void)setAnswerFormat:(ORKAnswerFormat *)arg1 ;
-(BOOL)singleChoice;
-(ORKTextChoice *)choice;
-(unsigned long long)choiceIndex;
-(double)labelWidth;
@end

