/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/_ORKFormItemTextFieldBasedCell.h>

@class UIDatePicker, NSDateFormatter;

@interface _ORKFormItemDateCell : _ORKFormItemTextFieldBasedCell {

	UIDatePicker* _picker;
	long long _questionType;
	NSDateFormatter* _labelFormatter;

}
-(void)setFormItem:(id)arg1 ;
-(void)_cellInit;
-(void)_answerDidChange;
-(void)_inputValueDidChange;
-(void)setDefaultAnswer:(id)arg1 ;
-(void)_loadPicker;
-(id)_labelFormatterWithCalendar:(id)arg1 ;
-(void)dealloc;
-(BOOL)textFieldShouldBeginEditing:(id)arg1 ;
-(BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(NSRange)arg2 replacementString:(id)arg3 ;
-(BOOL)textFieldShouldClear:(id)arg1 ;
-(void)setAnswer:(id)arg1 ;
-(void)_currentLocaleDidChange:(id)arg1 ;
@end

