/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:12 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSArray;

@interface _ORKObserver : NSObject {

	BOOL _observing;
	NSArray* _keyPaths;
	id _target;
	void* _context;
	id _responder;
	SEL _action;

}

@property (nonatomic,retain) NSArray * keyPaths;               //@synthesize keyPaths=_keyPaths - In the implementation block
@property (nonatomic,retain) id target;                        //@synthesize target=_target - In the implementation block
@property (assign,nonatomic) BOOL observing;                   //@synthesize observing=_observing - In the implementation block
@property (assign,nonatomic) void* context;                    //@synthesize context=_context - In the implementation block
@property (assign,nonatomic,__weak) id responder;              //@synthesize responder=_responder - In the implementation block
@property (assign,nonatomic) SEL action;                       //@synthesize action=_action - In the implementation block
-(NSArray *)keyPaths;
-(void)setObserving:(BOOL)arg1 ;
-(void)setKeyPaths:(NSArray *)arg1 ;
-(BOOL)observing;
-(void)startObserving;
-(void)dealloc;
-(void)setTarget:(id)arg1 ;
-(void)setResponder:(id)arg1 ;
-(SEL)action;
-(id)target;
-(id)responder;
-(void*)context;
-(void)setContext:(void*)arg1 ;
-(void)setAction:(SEL)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)_stopObserving;
@end

