/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKActiveStepViewController.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@class _ORKTappingContentView, UIGestureRecognizer, NSMutableArray, NSString;

@interface _ORKTappingIntervalStepViewController : ORKActiveStepViewController <UIGestureRecognizerDelegate> {

	_ORKTappingContentView* _tappingContentView;
	double _tappingStart;
	BOOL _expired;
	CGRect _buttonRect1;
	CGRect _buttonRect2;
	CGSize _viewSize;
	unsigned long long _hitButtonCount;
	UIGestureRecognizer* _touchDownRecognizer;
	NSMutableArray* _samples;

}

@property (nonatomic,retain) NSMutableArray * samples;              //@synthesize samples=_samples - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithStep:(id)arg1 ;
-(void)_countDownTimerFired:(id)arg1 finished:(BOOL)arg2 ;
-(void)_initializeInternalButtonItems;
-(void)stepDidFinish;
-(void)buttonPressed:(id)arg1 forEvent:(id)arg2 ;
-(void)_receiveTouch:(id)arg1 onButton:(long long)arg2 ;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)start;
-(id)result;
-(NSMutableArray *)samples;
-(void)setSamples:(NSMutableArray *)arg1 ;
@end

