/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@protocol _ORKConsentReviewControllerDelegate;
@class UIToolbar, NSLayoutConstraint, NSString, UIWebView;

@interface _ORKConsentReviewController : UIViewController {

	UIToolbar* _toolbar;
	NSLayoutConstraint* _toolbarHeightConstraint;
	NSString* _htmlString;
	UIWebView* _webView;
	id<_ORKConsentReviewControllerDelegate> _delegate;
	NSString* _localizedReasonForConsent;

}

@property (nonatomic,retain) UIWebView * webView;                                                  //@synthesize webView=_webView - In the implementation block
@property (assign,nonatomic,__weak) id<_ORKConsentReviewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSString * localizedReasonForConsent;                                 //@synthesize localizedReasonForConsent=_localizedReasonForConsent - In the implementation block
-(id)initWithHtml:(id)arg1 delegate:(id)arg2 ;
-(void)setLocalizedReasonForConsent:(NSString *)arg1 ;
-(NSString *)localizedReasonForConsent;
-(void)doAck;
-(void)ack;
-(void)cancel;
-(void)setDelegate:(id<_ORKConsentReviewControllerDelegate>)arg1 ;
-(id<_ORKConsentReviewControllerDelegate>)delegate;
-(void)viewDidLoad;
-(UIWebView *)webView;
-(void)setWebView:(UIWebView *)arg1 ;
@end

