/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <UIKit/UIView.h>

@class ORKSubheadlineLabel, _ORKQuantityLabel, _ORKTintedImageView, UIView, NSString, UIImage, UILabel;

@interface _ORKActiveStepQuantityView : UIView {

	ORKSubheadlineLabel* _titleLabel;
	_ORKQuantityLabel* _valueLabel;
	_ORKTintedImageView* _imageView;
	UIView* _valueHolder;
	BOOL _enabled;
	NSString* _title;
	NSString* _value;
	UIImage* _image;

}

@property (nonatomic,retain) NSString * title;                    //@synthesize title=_title - In the implementation block
@property (nonatomic,retain) NSString * value;                    //@synthesize value=_value - In the implementation block
@property (nonatomic,retain) UIImage * image;                     //@synthesize image=_image - In the implementation block
@property (assign,nonatomic) BOOL enabled;                        //@synthesize enabled=_enabled - In the implementation block
@property (nonatomic,readonly) UILabel * titleLabel;              //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,readonly) UILabel * valueLabel;              //@synthesize valueLabel=_valueLabel - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setImage:(UIImage *)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)title;
-(void)setValue:(NSString *)arg1 ;
-(UIImage *)image;
-(void)setEnabled:(BOOL)arg1 ;
-(NSString *)value;
-(id)accessibilityLabel;
-(UILabel *)titleLabel;
-(void)updateConstraints;
-(BOOL)enabled;
-(id)accessibilityValue;
-(unsigned long long)accessibilityTraits;
-(BOOL)isAccessibilityElement;
-(UILabel *)valueLabel;
@end

