/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSArray;

@interface _ORKObjectObserver : NSObject {

	NSArray* _keys;
	BOOL _observing;
	SEL _selector;
	id _object;

}

@property (assign) id object;              //@synthesize object=_object - In the implementation block
-(id)initWithObject:(id)arg1 keys:(id)arg2 selector:(SEL)arg3 ;
-(void)dealloc;
-(id)object;
-(void)resume;
-(void)setObject:(id)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)pause;
-(void)_stopObserving;
@end

