/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:12 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKActiveStepViewController.h>
#import <ResearchKit/ORKHealthQuantityTypeRecorderDelegate.h>
#import <ResearchKit/ORKPedometerRecorderDelegate.h>

@class _ORKFitnessContentView, NSNumberFormatter, NSString;

@interface _ORKFitnessStepViewController : ORKActiveStepViewController <ORKHealthQuantityTypeRecorderDelegate, ORKPedometerRecorderDelegate> {

	long long _intendedSteps;
	_ORKFitnessContentView* _contentView;
	NSNumberFormatter* _hrFormatter;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithStep:(id)arg1 ;
-(void)_stepDidChange;
-(id)fitnessStep;
-(void)recordersDidChange;
-(void)_countDownTimerFired:(id)arg1 finished:(BOOL)arg2 ;
-(void)_updateHeartRateWithQuantity:(id)arg1 unit:(id)arg2 ;
-(void)_updateDistance:(double)arg1 ;
-(void)healthQuantityTypeRecorderDidUpdate:(id)arg1 ;
-(void)pedometerRecorderDidUpdate:(id)arg1 ;
-(void)didReceiveMemoryWarning;
-(void)viewDidLoad;
@end

