/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:12 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <ResearchKit/ORKSignatureViewDelegate.h>

@protocol _ORKConsentSignatureControllerDelegate;
@class NSString, ORKConsentSigningView, ORKSignatureView;

@interface _ORKConsentSignatureController : UIViewController <ORKSignatureViewDelegate> {

	id<_ORKConsentSignatureControllerDelegate> _delegate;
	NSString* _localizedContinueButtonTitle;
	ORKConsentSigningView* _signingView;

}

@property (assign,nonatomic,__weak) id<_ORKConsentSignatureControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) ORKSignatureView * signatureView; 
@property (nonatomic,retain) NSString * localizedContinueButtonTitle;                                 //@synthesize localizedContinueButtonTitle=_localizedContinueButtonTitle - In the implementation block
@property (nonatomic,retain) ORKConsentSigningView * signingView;                                     //@synthesize signingView=_signingView - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(ORKSignatureView *)signatureView;
-(void)setLocalizedContinueButtonTitle:(NSString *)arg1 ;
-(void)_updateContinueButtonItem;
-(NSString *)localizedContinueButtonTitle;
-(void)signatureViewDidEditImage:(id)arg1 ;
-(ORKConsentSigningView *)signingView;
-(void)setSigningView:(ORKConsentSigningView *)arg1 ;
-(void)setDelegate:(id<_ORKConsentSignatureControllerDelegate>)arg1 ;
-(id<_ORKConsentSignatureControllerDelegate>)delegate;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidLoad;
-(void)done;
-(void)_clearAction:(id)arg1 ;
@end

