/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:12 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@class UIView, NSLayoutConstraint, NSArray, UIScrollView, UITableView, ORKStepHeaderView, ORKContinueSkipContainerView, NSString;

@interface _ORKTableContainerView : UIView <UIGestureRecognizerDelegate> {

	UIView* _realFooterView;
	NSLayoutConstraint* _bottomConstraint;
	NSArray* _constraints;
	double _keyboardOverlap;
	BOOL _keyboardIsUp;
	UIScrollView* _scrollView;
	UITableView* _tableView;
	ORKStepHeaderView* _stepHeaderView;
	ORKContinueSkipContainerView* _continueSkipContainerView;

}

@property (nonatomic,readonly) UITableView * tableView;                                               //@synthesize tableView=_tableView - In the implementation block
@property (nonatomic,readonly) ORKStepHeaderView * stepHeaderView;                                    //@synthesize stepHeaderView=_stepHeaderView - In the implementation block
@property (nonatomic,readonly) ORKContinueSkipContainerView * continueSkipContainerView;              //@synthesize continueSkipContainerView=_continueSkipContainerView - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_tapOffAction:(id)arg1 ;
-(void)_updateContinueButtonConstraints;
-(BOOL)_view:(id)arg1 hasFirstResponderOrTableViewCellContainingPoint:(CGPoint)arg2 ;
-(void)_registerForKeyboardNotifications:(BOOL)arg1 ;
-(void)keyboardFrameWillChange:(id)arg1 ;
-(CGSize)_keyboardIntersectionSizeFromNotification:(id)arg1 ;
-(void)scrollCellVisible:(id)arg1 animated:(BOOL)arg2 ;
-(void)_updateToInsets:(UIEdgeInsets)arg1 ;
-(void)_animateLayoutForKeyboardNotification:(id)arg1 ;
-(ORKStepHeaderView *)stepHeaderView;
-(ORKContinueSkipContainerView *)continueSkipContainerView;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2 ;
-(void)willMoveToWindow:(id)arg1 ;
-(void)updateConstraints;
-(UITableView *)tableView;
-(void)keyboardWillShow:(id)arg1 ;
-(void)keyboardWillHide:(id)arg1 ;
@end

