/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/_ORKFormItemCell.h>
#import <UIKit/UITextFieldDelegate.h>

@class _ORKTextFieldView, NSString;

@interface _ORKFormItemTextFieldBasedCell : _ORKFormItemCell <UITextFieldDelegate> {

	BOOL _editingHighlight;
	_ORKTextFieldView* _textFieldView;

}

@property (nonatomic,readonly) _ORKTextFieldView * textFieldView;              //@synthesize textFieldView=_textFieldView - In the implementation block
@property (assign,nonatomic) BOOL editingHighlight;                            //@synthesize editingHighlight=_editingHighlight - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_cellInit;
-(id)initWithReuseIdentifier:(id)arg1 formItem:(id)arg2 answer:(id)arg3 maxLabelWidth:(double)arg4 screenType:(long long)arg5 ;
-(void)_inputValueDidClear;
-(void)setEditingHighlight:(BOOL)arg1 ;
-(BOOL)editingHighlight;
-(void)dealloc;
-(BOOL)resignFirstResponder;
-(BOOL)becomeFirstResponder;
-(id)label;
-(BOOL)textFieldShouldBeginEditing:(id)arg1 ;
-(void)textFieldDidBeginEditing:(id)arg1 ;
-(void)textFieldDidEndEditing:(id)arg1 ;
-(BOOL)textFieldShouldClear:(id)arg1 ;
-(BOOL)textFieldShouldReturn:(id)arg1 ;
-(void)updateConstraints;
-(void)setLabel:(id)arg1 ;
-(id)textField;
-(BOOL)isAccessibilityElement;
-(_ORKTextFieldView *)textFieldView;
-(id)formattedValue;
-(id)shortenedFormattedValue;
-(void)updateValueLabel;
@end

