/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKActiveStepViewController.h>
#import <ResearchKit/ORKPedometerRecorderDelegate.h>

@class _ORKWalkingContentView, NSString;

@interface _ORKWalkingTaskStepViewController : ORKActiveStepViewController <ORKPedometerRecorderDelegate> {

	long long _intendedSteps;
	_ORKWalkingContentView* _contentView;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithStep:(id)arg1 ;
-(void)_stepDidChange;
-(void)pedometerRecorderDidUpdate:(id)arg1 ;
-(id)walkingTaskStep;
-(void)didReceiveMemoryWarning;
-(void)viewDidLoad;
@end

