/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKActiveStepViewController.h>

@class _ORKCountdownView;

@interface _ORKCountdownStepViewController : ORKActiveStepViewController {

	long long _countDown;
	_ORKCountdownView* _countdownView;

}

@property (nonatomic,retain) _ORKCountdownView * countdownView;              //@synthesize countdownView=_countdownView - In the implementation block
-(id)initWithStep:(id)arg1 ;
-(void)_countDownTimerFired:(id)arg1 finished:(BOOL)arg2 ;
-(void)_updateCountdownLabel;
-(_ORKCountdownView *)countdownView;
-(void)setCountdownView:(_ORKCountdownView *)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)setStep:(id)arg1 ;
@end

