/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <UIKit/UIView.h>

@class NSArray, NSTimer;

@interface _ORKWalkingProgressView : UIView {

	NSArray* _circles;
	long long _index;
	NSTimer* _timer;
	long long _count;

}

@property (assign,nonatomic) long long count;              //@synthesize count=_count - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)didMoveToWindow;
-(long long)count;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(CGSize)intrinsicContentSize;
-(void)setCount:(long long)arg1 ;
-(void)stopAnimating;
-(void)startAnimating;
-(void)setIndex:(long long)arg1 ;
-(void)incrementIndex;
@end

