/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@protocol _ORKFormItemCellDelegate;
@class ORKFormItem, ORKCaption1Label, UITableView, NSMutableArray;

@interface _ORKFormItemCell : UITableViewCell {

	BOOL _haveChangedAnswer;
	id<_ORKFormItemCellDelegate> _delegate;
	id _answer;
	ORKFormItem* _formItem;
	id _defaultAnswer;
	double _maxLabelWidth;
	long long _screenType;
	double _expectedLayoutWidth;
	ORKCaption1Label* _labelLabel;
	UITableView* __parentTableView;
	NSMutableArray* _myConstraints;

}

@property (assign,nonatomic,__weak) id<_ORKFormItemCellDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) id answer;                                                   //@synthesize answer=_answer - In the implementation block
@property (nonatomic,retain) ORKFormItem * formItem;                                    //@synthesize formItem=_formItem - In the implementation block
@property (nonatomic,copy) id defaultAnswer;                                            //@synthesize defaultAnswer=_defaultAnswer - In the implementation block
@property (assign,nonatomic) double maxLabelWidth;                                      //@synthesize maxLabelWidth=_maxLabelWidth - In the implementation block
@property (assign,nonatomic) long long screenType;                                      //@synthesize screenType=_screenType - In the implementation block
@property (assign,nonatomic) double expectedLayoutWidth;                                //@synthesize expectedLayoutWidth=_expectedLayoutWidth - In the implementation block
@property (nonatomic,retain) ORKCaption1Label * labelLabel;                             //@synthesize labelLabel=_labelLabel - In the implementation block
@property (assign,nonatomic,__weak) UITableView * _parentTableView;                     //@synthesize _parentTableView=__parentTableView - In the implementation block
@property (assign,nonatomic) BOOL haveChangedAnswer;                                    //@synthesize haveChangedAnswer=_haveChangedAnswer - In the implementation block
@property (nonatomic,retain) NSMutableArray * myConstraints;                            //@synthesize myConstraints=_myConstraints - In the implementation block
-(void)_showValidityAlertWithMessage:(id)arg1 ;
-(void)setFormItem:(ORKFormItem *)arg1 ;
-(void)_cellInit;
-(void)setHaveChangedAnswer:(BOOL)arg1 ;
-(BOOL)haveChangedAnswer;
-(void)_setAnswer:(id)arg1 ;
-(void)_defaultAnswerDidChange;
-(void)_answerDidChange;
-(id)initWithReuseIdentifier:(id)arg1 formItem:(id)arg2 answer:(id)arg3 maxLabelWidth:(double)arg4 screenType:(long long)arg5 ;
-(void)setExpectedLayoutWidth:(double)arg1 ;
-(UITableView *)_parentTableView;
-(void)_inputValueDidChange;
-(void)_inputValueDidClear;
-(void)setDefaultAnswer:(id)arg1 ;
-(ORKFormItem *)formItem;
-(id)defaultAnswer;
-(double)maxLabelWidth;
-(void)setMaxLabelWidth:(double)arg1 ;
-(void)setScreenType:(long long)arg1 ;
-(double)expectedLayoutWidth;
-(void)setLabelLabel:(ORKCaption1Label *)arg1 ;
-(void)set_parentTableView:(UITableView *)arg1 ;
-(NSMutableArray *)myConstraints;
-(void)setMyConstraints:(NSMutableArray *)arg1 ;
-(void)setDelegate:(id<_ORKFormItemCellDelegate>)arg1 ;
-(id<_ORKFormItemCellDelegate>)delegate;
-(BOOL)resignFirstResponder;
-(BOOL)becomeFirstResponder;
-(void)prepareForReuse;
-(long long)screenType;
-(id)answer;
-(void)setAnswer:(id)arg1 ;
-(ORKCaption1Label *)labelLabel;
@end

