/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIImageView.h>

@class UIImage;

@interface _ORKTintedImageView : UIImageView {

	UIImage* _originalImage;
	BOOL _shouldApplyTint;

}

@property (assign,nonatomic) BOOL shouldApplyTint;              //@synthesize shouldApplyTint=_shouldApplyTint - In the implementation block
-(void)setShouldApplyTint:(BOOL)arg1 ;
-(id)_imageByTintingImage:(id)arg1 ;
-(BOOL)shouldApplyTint;
-(void)setImage:(id)arg1 ;
-(void)tintColorDidChange;
@end

