/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UIButton, NSString;

@interface _ORKChoiceButtonView : UIView {

	UIButton* _button;
	NSString* _labelText;

}

@property (nonatomic,retain) UIButton * button;               //@synthesize button=_button - In the implementation block
@property (nonatomic,copy) NSString * labelText;              //@synthesize labelText=_labelText - In the implementation block
-(id)initWithImageOption:(id)arg1 ;
-(void)setLabelText:(NSString *)arg1 ;
-(NSString *)labelText;
-(UIButton *)button;
-(void)setButton:(UIButton *)arg1 ;
@end

