/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:12 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface _ORKState : NSObject {

	long long _state;
	id _context;
	/*^block*/id _entryHandler;
	/*^block*/id _exitHandler;

}

@property (assign,nonatomic) long long state;                //@synthesize state=_state - In the implementation block
@property (assign,nonatomic,__weak) id context;              //@synthesize context=_context - In the implementation block
@property (nonatomic,copy) id entryHandler;                  //@synthesize entryHandler=_entryHandler - In the implementation block
@property (nonatomic,copy) id exitHandler;                   //@synthesize exitHandler=_exitHandler - In the implementation block
+(id)stateWithState:(long long)arg1 entryHandler:(/*^block*/id)arg2 exitHandler:(/*^block*/id)arg3 context:(id)arg4 ;
-(void)setEntryHandler:(id)arg1 ;
-(void)setExitHandler:(id)arg1 ;
-(id)entryHandler;
-(id)exitHandler;
-(long long)state;
-(void)setState:(long long)arg1 ;
-(id)context;
-(void)setContext:(id)arg1 ;
@end

