/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKStepViewController.h>
#import <ResearchKit/ORKRecorderDelegate.h>

@class ORKActiveStepView, ORKActiveStepTimer, NSArray, NSURL, UIView, UIImageView, NSString;

@interface ORKActiveStepViewController : ORKStepViewController <ORKRecorderDelegate> {

	ORKActiveStepView* _activeStepView;
	ORKActiveStepTimer* _activeStepTimer;
	NSArray* _recorderResults;
	unsigned _alertSound;
	NSURL* _alertSoundURL;
	BOOL _finished;
	BOOL _suspendIfInactive;
	BOOL _started;
	UIView* _customView;
	NSArray* _recorders;
	double _timerUpdateInterval;

}

@property (nonatomic,retain) UIView * customView;                               //@synthesize customView=_customView - In the implementation block
@property (nonatomic,readonly) UIImageView * imageView; 
@property (getter=isFinished,nonatomic,readonly) BOOL finished;                 //@synthesize finished=_finished - In the implementation block
@property (nonatomic,retain) NSArray * recorders;                               //@synthesize recorders=_recorders - In the implementation block
@property (assign,nonatomic) BOOL suspendIfInactive;                            //@synthesize suspendIfInactive=_suspendIfInactive - In the implementation block
@property (assign,getter=isStarted,nonatomic) BOOL started;                     //@synthesize started=_started - In the implementation block
@property (nonatomic,readonly) UIView * customViewContainer; 
@property (nonatomic,readonly) ORKActiveStepView * activeStepView; 
@property (nonatomic,readonly) double timeRemaining; 
@property (nonatomic,readonly) BOOL timerActive; 
@property (assign,nonatomic) double timerUpdateInterval;                        //@synthesize timerUpdateInterval=_timerUpdateInterval - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithStep:(id)arg1 ;
-(void)setSuspendIfInactive:(BOOL)arg1 ;
-(void)_stepDidChange;
-(ORKActiveStepView *)activeStepView;
-(void)recordersDidChange;
-(NSArray *)recorders;
-(void)_countDownTimerFired:(id)arg1 finished:(BOOL)arg2 ;
-(void)recorder:(id)arg1 didCompleteWithResult:(id)arg2 ;
-(void)recorder:(id)arg1 didFailWithError:(id)arg2 ;
-(void)setContinueButtonItem:(id)arg1 ;
-(void)setSkipButtonItem:(id)arg1 ;
-(void)setOutputDirectory:(id)arg1 ;
-(void)setLearnMoreButtonItem:(id)arg1 ;
-(void)_updateContinueButtonItem;
-(void)stepDidFinish;
-(void)setTimerUpdateInterval:(double)arg1 ;
-(BOOL)suspendIfInactive;
-(void)prepareStep;
-(id)activeStep;
-(UIView *)customViewContainer;
-(void)recordersWillStop;
-(void)setRecorders:(NSArray *)arg1 ;
-(void)_prepareRecorders;
-(void)recordersWillStart;
-(void)_startRecorders;
-(void)_playSound;
-(void)_stopRecorders;
-(double)timerUpdateInterval;
-(void)_resetTimer;
-(void)dealloc;
-(void)applicationDidBecomeActive:(id)arg1 ;
-(void)applicationWillResignActive:(id)arg1 ;
-(void)suspend;
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)decodeRestorableStateWithCoder:(id)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(UIImageView *)imageView;
-(UIView *)customView;
-(void)start;
-(void)resume;
-(void)setCustomView:(UIView *)arg1 ;
-(void)_startTimer;
-(id)result;
-(BOOL)isFinished;
-(BOOL)isStarted;
-(void)finish;
-(void)setStarted:(BOOL)arg1 ;
-(void)setFinished:(BOOL)arg1 ;
-(BOOL)timerActive;
-(double)timeRemaining;
@end

