/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKActiveStepCustomView.h>

@class ORKCountdownLabel, ORKTextButton, ORKActiveStep;

@interface ORKActiveStepTimerView : ORKActiveStepCustomView {

	BOOL _started;
	BOOL _registeredForNotifications;
	ORKCountdownLabel* _countDownLabel;
	ORKTextButton* _startTimerButton;
	ORKActiveStep* _step;

}

@property (nonatomic,retain) ORKCountdownLabel * countDownLabel;              //@synthesize countDownLabel=_countDownLabel - In the implementation block
@property (nonatomic,retain) ORKTextButton * startTimerButton;                //@synthesize startTimerButton=_startTimerButton - In the implementation block
@property (nonatomic,retain) ORKActiveStep * step;                            //@synthesize step=_step - In the implementation block
-(void)_startTimerButtonTapped:(id)arg1 ;
-(void)_setRegisteredForNotifications:(BOOL)arg1 ;
-(void)resetStep:(id)arg1 ;
-(void)startStep:(id)arg1 ;
-(void)suspendStep:(id)arg1 ;
-(void)resumeStep:(id)arg1 ;
-(void)finishStep:(id)arg1 ;
-(ORKCountdownLabel *)countDownLabel;
-(void)setCountDownLabel:(ORKCountdownLabel *)arg1 ;
-(ORKTextButton *)startTimerButton;
-(void)setStartTimerButton:(ORKTextButton *)arg1 ;
-(void)updateDisplay:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)didMoveToWindow;
-(void)updateConstraints;
-(void)setNeedsUpdateConstraints;
-(void)_applicationDidBecomeActive:(id)arg1 ;
-(ORKActiveStep *)step;
-(void)setStep:(ORKActiveStep *)arg1 ;
@end

