/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKSerialization.h>
#import <ResearchKit/NSSecureCoding.h>
#import <ResearchKit/NSCopying.h>

@class NSString;

@interface ORKAnswerFormat : NSObject <ORKSerialization, NSSecureCoding, NSCopying>

@property (readonly) long long questionType; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)choiceAnswerFormatWithStyle:(long long)arg1 textChoices:(id)arg2 ;
+(id)valuePickerAnswerFormatWithTextChoices:(id)arg1 ;
+(id)dateAnswerFormatWithDefaultDate:(id)arg1 minimumDate:(id)arg2 maximumDate:(id)arg3 calendar:(id)arg4 ;
+(id)decimalAnswerFormatWithUnit:(id)arg1 ;
+(id)integerAnswerFormatWithUnit:(id)arg1 ;
+(id)booleanAnswerFormat;
+(id)textAnswerFormat;
+(Class)_questionResultClass;
+(id)scaleAnswerFormatWithMaxValue:(long long)arg1 minValue:(long long)arg2 step:(long long)arg3 defaultValue:(long long)arg4 ;
+(id)continuousScaleAnswerFormatWithMaxValue:(double)arg1 minValue:(double)arg2 defaultValue:(double)arg3 maximumFractionDigits:(long long)arg4 ;
+(id)choiceAnswerFormatWithImageChoices:(id)arg1 ;
+(id)timeOfDayAnswerFormat;
+(id)timeOfDayAnswerFormatWithDefaultComponents:(id)arg1 ;
+(id)dateTimeAnswerFormat;
+(id)dateTimeAnswerFormatWithDefaultDate:(id)arg1 minimumDate:(id)arg2 maximumDate:(id)arg3 calendar:(id)arg4 ;
+(id)dateAnswerFormat;
+(id)textAnswerFormatWithMaximumLength:(long long)arg1 ;
+(id)timeIntervalAnswerFormat;
+(id)timeIntervalAnswerFormatWithDefaultInterval:(double)arg1 step:(long long)arg2 ;
+(BOOL)supportsSecureCoding;
-(id)dictionaryValue;
-(void)validateParameters;
-(id)_impliedAnswerFormat;
-(long long)questionType;
-(BOOL)_isAnswerValidWithString:(id)arg1 ;
-(id)_localizedInvalidValueStringWithAnswerString:(id)arg1 ;
-(BOOL)_isHealthKitAnswerFormat;
-(id)_healthKitObjectType;
-(id)_healthKitUserUnit;
-(id)_healthKitUnit;
-(void)_setHealthKitUserUnit:(id)arg1 ;
-(id)_resultWithIdentifier:(id)arg1 answer:(id)arg2 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)initWithDictionary:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)_calendar;
@end

