/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKVerticalContainerView.h>

@class _ORKTintedImageView, ORKActiveStep, ORKActiveStepCustomView;

@interface ORKActiveStepView : ORKVerticalContainerView {

	_ORKTintedImageView* _imageView;
	ORKActiveStep* _activeStep;
	ORKActiveStepCustomView* _activeCustomView;

}

@property (nonatomic,retain) ORKActiveStep * activeStep;                              //@synthesize activeStep=_activeStep - In the implementation block
@property (nonatomic,retain) ORKActiveStepCustomView * activeCustomView;              //@synthesize activeCustomView=_activeCustomView - In the implementation block
-(void)setActiveCustomView:(ORKActiveStepCustomView *)arg1 ;
-(void)updateTitle:(id)arg1 text:(id)arg2 ;
-(ORKActiveStep *)activeStep;
-(void)setActiveStep:(ORKActiveStep *)arg1 ;
-(ORKActiveStepCustomView *)activeCustomView;
-(void)_updateStepView;
-(id)initWithFrame:(CGRect)arg1 ;
@end

