/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableDictionary, HKHealthStore;

@interface ORKAnswerDefaultSource : NSObject {

	NSMutableDictionary* _unitsTable;
	HKHealthStore* _healthStore;

}

@property (nonatomic,readonly) HKHealthStore * healthStore;              //@synthesize healthStore=_healthStore - In the implementation block
+(id)sourceWithHealthStore:(id)arg1 ;
-(void)fetchDefaultValueForAnswerFormat:(id)arg1 handler:(/*^block*/id)arg2 ;
-(id)initWithHealthStore:(id)arg1 ;
-(void)_healthKitUserPreferencesDidChange:(id)arg1 ;
-(id)_defaultValueForCharacteristicType:(id)arg1 error:(id*)arg2 ;
-(void)updateHealthKitUnitForAnswerFormat:(id)arg1 force:(BOOL)arg2 ;
-(void)_fetchDefaultValueForQuantityType:(id)arg1 unit:(id)arg2 handler:(/*^block*/id)arg3 ;
-(id)defaultHealthKitUnitForAnswerFormat:(id)arg1 ;
-(HKHealthStore *)healthStore;
-(void)dealloc;
@end

