/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKRecorder.h>

@class ORKDataLogger, NSError, CMMotionManager;

@interface ORKAccelerometerRecorder : ORKRecorder {

	ORKDataLogger* _logger;
	NSError* _recordingError;
	double _frequency;
	CMMotionManager* _motionManager;
	double _uptime;

}

@property (nonatomic,readonly) double frequency;                           //@synthesize frequency=_frequency - In the implementation block
@property (nonatomic,retain) CMMotionManager * motionManager;              //@synthesize motionManager=_motionManager - In the implementation block
@property (assign,nonatomic) double uptime;                                //@synthesize uptime=_uptime - In the implementation block
-(void)finishRecordingWithError:(id)arg1 ;
-(void)setUptime:(double)arg1 ;
-(void)_doStopRecording;
-(id)_recorderType;
-(double)uptime;
-(void)setMotionManager:(CMMotionManager *)arg1 ;
-(CMMotionManager *)motionManager;
-(id)initWithFrequency:(double)arg1 step:(id)arg2 outputDirectory:(id)arg3 ;
-(id)_userInfo;
-(BOOL)isRecording;
-(void)dealloc;
-(double)frequency;
-(void)setFrequency:(double)arg1 ;
-(void)start;
-(id)mimeType;
-(void)_reset;
-(void)stop;
@end

