/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue, OS_dispatch_source;
@class NSObject;

@interface ORKActiveStepTimer : NSObject {

	unsigned long long _startTime;
	double _preExistingRuntime;
	NSObject*<OS_dispatch_queue> _queue;
	NSObject*<OS_dispatch_source> _timer;
	unsigned long long _backgroundTaskIdentifier;
	unsigned _isRunning;
	double _duration;
	double _interval;
	/*^block*/id _handler;

}

@property (assign,nonatomic) double duration;                //@synthesize duration=_duration - In the implementation block
@property (nonatomic,readonly) double interval;              //@synthesize interval=_interval - In the implementation block
@property (nonatomic,readonly) double runtime; 
@property (nonatomic,copy,readonly) id handler;              //@synthesize handler=_handler - In the implementation block
-(double)runtime;
-(id)initWithDuration:(double)arg1 interval:(double)arg2 runtime:(double)arg3 handler:(/*^block*/id)arg4 ;
-(void)_queue_pauseAtFinish:(BOOL)arg1 ;
-(double)_queue_runtime;
-(void)_queue_resume;
-(void)_queue_reset;
-(void)_queue_event;
-(void)_queue_assertBackgroundTask;
-(void)_queue_releaseBackgroundTask;
-(void)_hiqueue_event;
-(void)_queue_clearTimer;
-(void)dealloc;
-(double)duration;
-(void)setDuration:(double)arg1 ;
-(id)handler;
-(void)resume;
-(void)reset;
-(double)interval;
-(void)pause;
@end

