/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKQuestionResult.h>

@class NSNumber;

@interface ORKBooleanQuestionResult : ORKQuestionResult {

	NSNumber* _booleanAnswer;

}

@property (nonatomic,copy) NSNumber * booleanAnswer;              //@synthesize booleanAnswer=_booleanAnswer - In the implementation block
+(Class)answerClass;
-(id)_serializableDictionary;
-(NSNumber *)booleanAnswer;
-(void)setBooleanAnswer:(NSNumber *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)answer;
-(void)setAnswer:(id)arg1 ;
@end

