/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKTextButton.h>

@class UIColor;

@interface ORKBorderedButton : ORKTextButton {

	UIColor* _normalTintColor;
	UIColor* _normalHighlightTintColor;
	UIColor* _disableTintColor;
	double _fadeDelay;

}

@property (assign,nonatomic) double fadeDelay;              //@synthesize fadeDelay=_fadeDelay - In the implementation block
+(id)defaultFont;
-(void)_init_ORKTextButton;
-(void)setFadeDelay:(double)arg1 ;
-(void)_updateBorderColor;
-(double)fadeDelay;
-(void)_fadeHighlightColor;
-(void)setEnabled:(BOOL)arg1 ;
-(void)tintColorDidChange;
-(void)setHighlighted:(BOOL)arg1 ;
@end

