/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKStepViewController.h>
#import <UIKit/UIPageViewControllerDelegate.h>
#import <ResearchKit/ORKStepViewControllerDelegate.h>
#import <ResearchKit/_ORKConsentReviewControllerDelegate.h>
#import <ResearchKit/_ORKConsentSignatureControllerDelegate.h>

@class ORKConsentSignature, UIPageViewController, NSMutableArray, NSString, UIImage;

@interface ORKConsentReviewStepViewController : ORKStepViewController <UIPageViewControllerDelegate, ORKStepViewControllerDelegate, _ORKConsentReviewControllerDelegate, _ORKConsentSignatureControllerDelegate> {

	ORKConsentSignature* _currentSignature;
	UIPageViewController* _pageViewController;
	NSMutableArray* _pageIndices;
	NSString* _signatureFirst;
	NSString* _signatureLast;
	UIImage* _signatureImage;
	BOOL _documentReviewed;
	unsigned long long _currentPageIndex;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_stepDidChange;
-(void)_updateNavLeftBarButtonItem;
-(BOOL)stepViewControllerHasPreviousStep:(id)arg1 ;
-(BOOL)stepViewControllerHasNextStep:(id)arg1 ;
-(void)stepViewControllerResultDidChange:(id)arg1 ;
-(void)stepViewController:(id)arg1 didFinishWithNavigationDirection:(long long)arg2 ;
-(void)_notifyDelegateOnResultChange;
-(void)consentSignatureControllerDidSign:(id)arg1 ;
-(void)stepViewControllerDidFail:(id)arg1 withError:(id)arg2 ;
-(id)_viewControllerForIndex:(unsigned long long)arg1 ;
-(void)_updateBackButton;
-(void)_goToPreviousPage;
-(id)consentReviewStep;
-(void)_goToPage:(long long)arg1 animated:(BOOL)arg2 ;
-(id)_goToPreviousPageButtonItem;
-(void)_navigateDelta:(long long)arg1 ;
-(id)_makeNameFormViewController;
-(id)_makeDocumentReviewViewController;
-(id)_makeSignatureViewController;
-(void)consentReviewControllerDidAcknowledge:(id)arg1 ;
-(void)consentReviewControllerDidCancel:(id)arg1 ;
-(id)initWithConsentReviewStep:(id)arg1 result:(id)arg2 ;
-(void)consentSignatureControllerDidCancel:(id)arg1 ;
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)decodeRestorableStateWithCoder:(id)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(id)result;
@end

