/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <UIKit/UIView.h>

@class NSLayoutConstraint, NSMutableArray, UIBarButtonItem, ORKContinueButton, ORKTextButton;

@interface ORKContinueSkipContainerView : UIView {

	NSLayoutConstraint* _gapConstraint;
	NSMutableArray* _localConstraints;
	BOOL _continueButtonJustTapped;
	BOOL _continueEnabled;
	BOOL _neverHasContinueButton;
	BOOL _useNextForSkip;
	BOOL _optional;
	UIBarButtonItem* _skipButtonItem;
	UIBarButtonItem* _continueButtonItem;
	double _topMargin;
	double _bottomMargin;
	ORKContinueButton* _continueButton;
	ORKTextButton* _skipButton;

}

@property (nonatomic,retain) UIBarButtonItem * skipButtonItem;                  //@synthesize skipButtonItem=_skipButtonItem - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * continueButtonItem;              //@synthesize continueButtonItem=_continueButtonItem - In the implementation block
@property (assign,nonatomic) BOOL continueEnabled;                              //@synthesize continueEnabled=_continueEnabled - In the implementation block
@property (assign,nonatomic) BOOL neverHasContinueButton;                       //@synthesize neverHasContinueButton=_neverHasContinueButton - In the implementation block
@property (assign,nonatomic) double topMargin;                                  //@synthesize topMargin=_topMargin - In the implementation block
@property (assign,nonatomic) double bottomMargin;                               //@synthesize bottomMargin=_bottomMargin - In the implementation block
@property (nonatomic,retain) ORKContinueButton * continueButton;                //@synthesize continueButton=_continueButton - In the implementation block
@property (nonatomic,retain) ORKTextButton * skipButton;                        //@synthesize skipButton=_skipButton - In the implementation block
@property (assign,nonatomic) BOOL useNextForSkip;                               //@synthesize useNextForSkip=_useNextForSkip - In the implementation block
@property (assign,getter=isOptional,nonatomic) BOOL optional;                   //@synthesize optional=_optional - In the implementation block
-(void)setContinueButtonItem:(UIBarButtonItem *)arg1 ;
-(void)setSkipButtonItem:(UIBarButtonItem *)arg1 ;
-(UIBarButtonItem *)continueButtonItem;
-(UIBarButtonItem *)skipButtonItem;
-(void)_updateContinueAndSkipEnabled;
-(void)setContinueEnabled:(BOOL)arg1 ;
-(void)_updateConstraintConstants;
-(BOOL)hasContinueOrSkip;
-(void)setUseNextForSkip:(BOOL)arg1 ;
-(void)setNeverHasContinueButton:(BOOL)arg1 ;
-(void)_skipButtonAction:(id)arg1 ;
-(void)_continueButtonAction:(id)arg1 ;
-(void)_skipAction:(id)arg1 ;
-(BOOL)_skipButtonHidden;
-(BOOL)neverHasContinueButton;
-(BOOL)_neverHasSkipButton;
-(double)_skipButtonAlpha;
-(ORKContinueButton *)continueButton;
-(BOOL)continueEnabled;
-(void)setContinueButton:(ORKContinueButton *)arg1 ;
-(BOOL)useNextForSkip;
-(BOOL)isOptional;
-(void)setOptional:(BOOL)arg1 ;
-(double)topMargin;
-(void)setTopMargin:(double)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)updateConstraints;
-(void)setSkipButton:(ORKTextButton *)arg1 ;
-(ORKTextButton *)skipButton;
-(double)bottomMargin;
-(void)setBottomMargin:(double)arg1 ;
-(void)_continueAction:(id)arg1 ;
@end

