/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKQuestionStep.h>

@class NSString;

@interface ORKConsentSharingStep : ORKQuestionStep {

	NSString* _localizedLearnMoreHTMLContent;

}

@property (nonatomic,copy) NSString * localizedLearnMoreHTMLContent;              //@synthesize localizedLearnMoreHTMLContent=_localizedLearnMoreHTMLContent - In the implementation block
+(Class)_stepViewControllerClass;
-(BOOL)_shouldShowProgress;
-(BOOL)useSurveyMode;
-(NSString *)localizedLearnMoreHTMLContent;
-(void)setLocalizedLearnMoreHTMLContent:(NSString *)arg1 ;
-(id)initWithIdentifier:(id)arg1 investigatorShortDescription:(id)arg2 investigatorLongDescription:(id)arg3 localizedLearnMoreHTMLContent:(id)arg4 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

