/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKBorderedButton.h>

@interface ORKContinueButton : ORKBorderedButton {

	BOOL _isDoneButton;

}

@property (assign,nonatomic) BOOL isDoneButton;              //@synthesize isDoneButton=_isDoneButton - In the implementation block
+(id)defaultFont;
-(BOOL)isDoneButton;
-(void)setIsDoneButton:(BOOL)arg1 ;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)didMoveToWindow;
-(CGSize)intrinsicContentSize;
@end

