/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UIImageView, ORKSelectionTitleLabel, ORKSelectionSubTitleLabel;

@interface ORKChoiceViewCell : UITableViewCell {

	UIImageView* _checkView;
	BOOL _selectedItem;
	ORKSelectionTitleLabel* _shortLabel;
	ORKSelectionSubTitleLabel* _longLabel;

}

@property (nonatomic,retain) ORKSelectionTitleLabel * shortLabel;                  //@synthesize shortLabel=_shortLabel - In the implementation block
@property (nonatomic,retain) ORKSelectionSubTitleLabel * longLabel;                //@synthesize longLabel=_longLabel - In the implementation block
@property (assign,getter=isSelectedItem,nonatomic) BOOL selectedItem;              //@synthesize selectedItem=_selectedItem - In the implementation block
+(double)suggestedCellHeightForShortText:(id)arg1 LongText:(id)arg2 inTableView:(id)arg3 ;
-(ORKSelectionSubTitleLabel *)longLabel;
-(ORKSelectionTitleLabel *)shortLabel;
-(void)_updateSelectedItem;
-(void)setShortLabel:(ORKSelectionTitleLabel *)arg1 ;
-(void)setLongLabel:(ORKSelectionSubTitleLabel *)arg1 ;
-(BOOL)isSelectedItem;
-(void)layoutSubviews;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(id)accessibilityLabel;
-(void)setSelectedItem:(BOOL)arg1 ;
@end

