/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class ORKConsentSceneView, ORKConsentSection, UIBarButtonItem, NSString;

@interface ORKConsentSceneViewController : UIViewController {

	ORKConsentSceneView* _sceneView;
	BOOL _imageHidden;
	ORKConsentSection* _section;
	UIBarButtonItem* _continueButtonItem;
	NSString* _learnMoreButtonTitle;

}

@property (nonatomic,readonly) ORKConsentSection * section;                     //@synthesize section=_section - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * continueButtonItem;              //@synthesize continueButtonItem=_continueButtonItem - In the implementation block
@property (nonatomic,retain) NSString * learnMoreButtonTitle;                   //@synthesize learnMoreButtonTitle=_learnMoreButtonTitle - In the implementation block
@property (assign,nonatomic) BOOL imageHidden;                                  //@synthesize imageHidden=_imageHidden - In the implementation block
-(void)setContinueButtonItem:(UIBarButtonItem *)arg1 ;
-(UIBarButtonItem *)continueButtonItem;
-(void)setLearnMoreButtonTitle:(NSString *)arg1 ;
-(NSString *)learnMoreButtonTitle;
-(void)showContent:(id)arg1 ;
-(BOOL)imageHidden;
-(void)setImageHidden:(BOOL)arg1 ;
-(ORKConsentSection *)section;
-(long long)adaptivePresentationStyleForPresentationController:(id)arg1 ;
-(void)loadView;
-(void)viewDidLoad;
-(id)initWithSection:(id)arg1 ;
@end

