/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKStep.h>

@class ORKConsentDocument, ORKConsentSignature, NSString;

@interface ORKConsentReviewStep : ORKStep {

	ORKConsentDocument* _consentDocument;
	ORKConsentSignature* _signature;
	NSString* _reasonForConsent;

}

@property (nonatomic,readonly) ORKConsentDocument * consentDocument;              //@synthesize consentDocument=_consentDocument - In the implementation block
@property (nonatomic,readonly) ORKConsentSignature * signature;                   //@synthesize signature=_signature - In the implementation block
@property (nonatomic,copy) NSString * reasonForConsent;                           //@synthesize reasonForConsent=_reasonForConsent - In the implementation block
+(Class)_stepViewControllerClass;
-(ORKConsentDocument *)consentDocument;
-(id)dictionaryValue;
-(BOOL)_shouldShowProgress;
-(NSString *)reasonForConsent;
-(id)initWithIdentifier:(id)arg1 signature:(id)arg2 inDocument:(id)arg3 ;
-(void)setReasonForConsent:(NSString *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)initWithDictionary:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(ORKConsentSignature *)signature;
@end

