/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKAnswerFormat.h>

@class NSDate, NSCalendar;

@interface ORKDateAnswerFormat : ORKAnswerFormat {

	long long _style;
	NSDate* _defaultDate;
	NSDate* _minimumDate;
	NSDate* _maximumDate;
	NSCalendar* _calendar;

}

@property (readonly) long long style;                         //@synthesize style=_style - In the implementation block
@property (copy,readonly) NSDate * defaultDate;               //@synthesize defaultDate=_defaultDate - In the implementation block
@property (copy,readonly) NSDate * minimumDate;               //@synthesize minimumDate=_minimumDate - In the implementation block
@property (copy,readonly) NSDate * maximumDate;               //@synthesize maximumDate=_maximumDate - In the implementation block
@property (copy,readonly) NSCalendar * calendar;              //@synthesize calendar=_calendar - In the implementation block
+(Class)_questionResultClass;
+(void)initialize;
-(id)dictionaryValue;
-(long long)questionType;
-(id)_pickerDefaultDate;
-(id)_currentCalendar;
-(id)_pickerMinimumDate;
-(id)_pickerMaximumDate;
-(id)initWithStyle:(long long)arg1 defaultDate:(id)arg2 minimumDate:(id)arg3 maximumDate:(id)arg4 calendar:(id)arg5 ;
-(id)_resultDateFormatter;
-(id)_dateFromString:(id)arg1 ;
-(id)_stringFromDate:(id)arg1 ;
-(NSDate *)defaultDate;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)initWithDictionary:(id)arg1 ;
-(long long)style;
-(id)initWithStyle:(long long)arg1 ;
-(id)_calendar;
-(NSCalendar *)calendar;
-(NSDate *)minimumDate;
-(NSDate *)maximumDate;
@end

