/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKDataLoggerExtendedDelegate.h>
#import <ResearchKit/ORKDataLoggerDelegate.h>

@protocol OS_dispatch_queue, OS_dispatch_group, ORKDataLoggerManagerDelegate;
@class NSURL, NSMutableDictionary, NSObject, _ORKObjectObserver, NSString;

@interface ORKDataLoggerManager : NSObject <ORKDataLoggerExtendedDelegate, ORKDataLoggerDelegate> {

	NSURL* _directory;
	NSMutableDictionary* _records;
	NSMutableDictionary* _observers;
	BOOL _pendingUploadDelegateSent;
	BOOL _totalBytesDelegateSent;
	NSObject*<OS_dispatch_queue> _queue;
	BOOL _updateBytesPending;
	NSObject*<OS_dispatch_group> _updateBytesGroup;
	_ORKObjectObserver* _observer;
	id<ORKDataLoggerManagerDelegate> _delegate;
	unsigned long long _pendingUploadBytesThreshold;
	unsigned long long _totalBytesThreshold;
	unsigned long long _pendingUploadBytes;
	unsigned long long _totalBytes;

}

@property (__weak) id<ORKDataLoggerManagerDelegate> delegate;                   //@synthesize delegate=_delegate - In the implementation block
@property (assign) unsigned long long pendingUploadBytesThreshold;              //@synthesize pendingUploadBytesThreshold=_pendingUploadBytesThreshold - In the implementation block
@property (assign) unsigned long long totalBytesThreshold;                      //@synthesize totalBytesThreshold=_totalBytesThreshold - In the implementation block
@property (assign) unsigned long long pendingUploadBytes;                       //@synthesize pendingUploadBytes=_pendingUploadBytes - In the implementation block
@property (assign) unsigned long long totalBytes;                               //@synthesize totalBytes=_totalBytes - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dataLoggerThresholdsDidChange:(id)arg1 ;
-(void)_queue_updateBytes;
-(void)dataLogger:(id)arg1 finishedLogFile:(id)arg2 ;
-(void)dataLoggerByteCountsDidChange:(id)arg1 ;
-(BOOL)enumerateLogsNeedingUpload:(/*^block*/id)arg1 error:(id*)arg2 ;
-(void)_loadConfiguration:(id)arg1 ;
-(void)_setNeedsUpdateBytes;
-(void)setPendingUploadBytesThreshold:(unsigned long long)arg1 ;
-(void)setTotalBytesThreshold:(unsigned long long)arg1 ;
-(unsigned long long)pendingUploadBytesThreshold;
-(unsigned long long)totalBytesThreshold;
-(id)_queue_configuration;
-(void)_queue_synchronizeConfiguration;
-(id)addDataLoggerForLogName:(id)arg1 formatter:(id)arg2 ;
-(id)_queue_addDataLoggerForLogName:(id)arg1 formatter:(id)arg2 ;
-(void)_queue_removeDataLogger:(id)arg1 ;
-(BOOL)_queue_enumerateLogsNeedingUpload:(/*^block*/id)arg1 error:(id*)arg2 ;
-(BOOL)_queue_removeUploadedFiles:(id)arg1 error:(id*)arg2 ;
-(BOOL)_queue_unmarkUploadedFiles:(id)arg1 error:(id*)arg2 ;
-(BOOL)_queue_removeOldAndUploadedLogsToThreshold:(unsigned long long)arg1 error:(id*)arg2 ;
-(void)setPendingUploadBytes:(unsigned long long)arg1 ;
-(id)initWithDirectory:(id)arg1 delegate:(id)arg2 ;
-(id)addJSONDataLoggerForLogName:(id)arg1 ;
-(void)removeDataLogger:(id)arg1 ;
-(id)dataLoggerForLogName:(id)arg1 ;
-(id)logNames;
-(BOOL)removeUploadedFiles:(id)arg1 error:(id*)arg2 ;
-(BOOL)unmarkUploadedFiles:(id)arg1 error:(id*)arg2 ;
-(BOOL)removeOldAndUploadedLogsToThreshold:(unsigned long long)arg1 error:(id*)arg2 ;
-(unsigned long long)pendingUploadBytes;
-(void)_configurationDidChange;
-(void)setDelegate:(id<ORKDataLoggerManagerDelegate>)arg1 ;
-(id<ORKDataLoggerManagerDelegate>)delegate;
-(unsigned long long)totalBytes;
-(void)setTotalBytes:(unsigned long long)arg1 ;
@end

