/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue, OS_dispatch_source, OS_dispatch_group, ORKDataLoggerDelegate;
@class NSURL, _ORKObjectObserver, NSString, NSFileHandle, NSObject, ORKLogFormatter;

@interface ORKDataLogger : NSObject {

	NSURL* _url;
	_ORKObjectObserver* _observer;
	NSString* _oldLogsPrefix;
	NSFileHandle* _currentFileHandle;
	NSObject*<OS_dispatch_queue> _queue;
	NSObject*<OS_dispatch_source> _directorySource;
	NSObject*<OS_dispatch_group> _directoryUpdateGroup;
	BOOL _directoryDirty;
	id<ORKDataLoggerDelegate> _delegate;
	ORKLogFormatter* _logFormatter;
	unsigned long long _maximumCurrentLogFileSize;
	double _maximumCurrentLogFileLifetime;
	unsigned long long _pendingBytes;
	unsigned long long _uploadedBytes;
	long long _fileProtectionMode;
	NSString* _logName;

}

@property (__weak) id<ORKDataLoggerDelegate> delegate;                        //@synthesize delegate=_delegate - In the implementation block
@property (retain) ORKLogFormatter * logFormatter;                            //@synthesize logFormatter=_logFormatter - In the implementation block
@property (assign) unsigned long long maximumCurrentLogFileSize;              //@synthesize maximumCurrentLogFileSize=_maximumCurrentLogFileSize - In the implementation block
@property (assign) double maximumCurrentLogFileLifetime;                      //@synthesize maximumCurrentLogFileLifetime=_maximumCurrentLogFileLifetime - In the implementation block
@property (assign) unsigned long long pendingBytes;                           //@synthesize pendingBytes=_pendingBytes - In the implementation block
@property (assign) unsigned long long uploadedBytes;                          //@synthesize uploadedBytes=_uploadedBytes - In the implementation block
@property (assign) long long fileProtectionMode;                              //@synthesize fileProtectionMode=_fileProtectionMode - In the implementation block
@property (copy) NSString * logName;                                          //@synthesize logName=_logName - In the implementation block
+(id)_nextUrlForDirectoryUrl:(id)arg1 logName:(id)arg2 ;
+(id)JSONDataLoggerWithDirectory:(id)arg1 logName:(id)arg2 delegate:(id)arg3 ;
-(void)finishCurrentLog;
-(BOOL)enumerateLogs:(/*^block*/id)arg1 error:(id*)arg2 ;
-(BOOL)appendObjects:(id)arg1 error:(id*)arg2 ;
-(BOOL)append:(id)arg1 error:(id*)arg2 ;
-(id)initWithDirectory:(id)arg1 logName:(id)arg2 formatter:(id)arg3 delegate:(id)arg4 ;
-(void)setFileProtectionMode:(long long)arg1 ;
-(void)_setLogName:(id)arg1 ;
-(void)_setLogFormatter:(id)arg1 ;
-(void)fileSizeLimitsDidChange;
-(void)_setupDirectorySource;
-(void)setMaximumCurrentLogFileSize:(unsigned long long)arg1 ;
-(void)setMaximumCurrentLogFileLifetime:(double)arg1 ;
-(ORKLogFormatter *)logFormatter;
-(long long)fileProtectionMode;
-(unsigned long long)maximumCurrentLogFileSize;
-(double)maximumCurrentLogFileLifetime;
-(void)_directoryUpdated;
-(void)_queue_rolloverIfNeeded;
-(void)_queue_rollover;
-(BOOL)_queue_enumerateLogs:(/*^block*/id)arg1 error:(id*)arg2 ;
-(BOOL)_queue_enumerateLogsUploaded:(BOOL)arg1 block:(/*^block*/id)arg2 error:(id*)arg3 ;
-(BOOL)_enumerateLogsUploaded:(BOOL)arg1 block:(/*^block*/id)arg2 error:(id*)arg3 ;
-(BOOL)_queue_append:(id)arg1 error:(id*)arg2 ;
-(BOOL)_queue_appendObjects:(id)arg1 error:(id*)arg2 ;
-(BOOL)_queue_markFileUploaded:(BOOL)arg1 atURL:(id)arg2 error:(id*)arg3 ;
-(BOOL)_queue_removeUploadedFiles:(id)arg1 withError:(id*)arg2 ;
-(BOOL)_queue_removeAllFilesWithError:(id*)arg1 ;
-(void)_queue_updateBytes;
-(void)_queue_setNeedsUpdateBytes;
-(BOOL)_urlMatchesLogName:(id)arg1 ;
-(id)currentLogFileURL;
-(void)_queue_closeAndRenameLog;
-(id)_queue_makeFileHandleWithError:(id*)arg1 ;
-(id)_queue_fileHandleWithError:(id*)arg1 ;
-(void)setPendingBytes:(unsigned long long)arg1 ;
-(void)setUploadedBytes:(unsigned long long)arg1 ;
-(id)_initWithDirectory:(id)arg1 configuration:(id)arg2 delegate:(id)arg3 ;
-(id)_fileHandle;
-(BOOL)enumerateLogsNeedingUpload:(/*^block*/id)arg1 error:(id*)arg2 ;
-(BOOL)enumerateLogsAlreadyUploaded:(/*^block*/id)arg1 error:(id*)arg2 ;
-(BOOL)markFileUploaded:(BOOL)arg1 atURL:(id)arg2 error:(id*)arg3 ;
-(BOOL)removeUploadedFiles:(id)arg1 withError:(id*)arg2 ;
-(BOOL)removeAllFilesWithError:(id*)arg1 ;
-(BOOL)isFileUploadedAtURL:(id)arg1 ;
-(unsigned long long)pendingBytes;
-(unsigned long long)uploadedBytes;
-(id)_configuration;
-(void)dealloc;
-(void)setDelegate:(id<ORKDataLoggerDelegate>)arg1 ;
-(id<ORKDataLoggerDelegate>)delegate;
-(NSString *)logName;
@end

