/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <UIKit/UIView.h>

@class EAGLContext;

@interface ORKEAGLMoviePlayerView : UIView {

	int _backingWidth;
	int _backingHeight;
	EAGLContext* _context;
	CVBufferRef _lumaTexture;
	CVBufferRef _chromaTexture;
	CVOpenGLESTextureCacheRef _videoTextureCache;
	unsigned _frameBufferHandle;
	unsigned _colorBufferHandle;
	const float* _preferredConversion;
	BOOL _haveSetup;
	float _preferredRotation;
	unsigned _program;
	CGSize _presentationRect;

}

@property (assign) float preferredRotation;              //@synthesize preferredRotation=_preferredRotation - In the implementation block
@property (assign) CGSize presentationRect;              //@synthesize presentationRect=_presentationRect - In the implementation block
@property (assign) unsigned program;                     //@synthesize program=_program - In the implementation block
+(Class)layerClass;
-(BOOL)loadShaders;
-(void)setupBuffers;
-(float)preferredRotation;
-(void)cleanUpTextures;
-(CGSize)presentationRect;
-(BOOL)compileShader:(unsigned*)arg1 type:(unsigned)arg2 URL:(id)arg3 ;
-(BOOL)consumePixelBuffer:(CVBufferRef)arg1 ;
-(void)setPreferredRotation:(float)arg1 ;
-(void)setPresentationRect:(CGSize)arg1 ;
-(void)setProgram:(unsigned)arg1 ;
-(unsigned)program;
-(void)render;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(BOOL)linkProgram:(unsigned)arg1 ;
-(BOOL)validateProgram:(unsigned)arg1 ;
-(void)setupGL;
@end

