/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKStepViewController.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>
#import <ResearchKit/_ORKFormItemCellDelegate.h>

@class ORKAnswerDefaultSource, ORKContinueSkipContainerView, NSMutableSet, NSMutableArray, _ORKTableContainerView, UITableView, ORKStepHeaderView, NSMutableDictionary, NSString;

@interface ORKFormStepViewController : ORKStepViewController <UITableViewDataSource, UITableViewDelegate, _ORKFormItemCellDelegate> {

	ORKAnswerDefaultSource* _defaultSource;
	ORKContinueSkipContainerView* _continueSkipView;
	NSMutableSet* _formItemCells;
	NSMutableArray* _sections;
	BOOL _skipped;
	_ORKTableContainerView* _tableContainer;
	UITableView* _tableView;
	ORKStepHeaderView* _headerView;
	NSMutableDictionary* _savedAnswers;
	NSMutableDictionary* _savedAnswerDates;
	NSMutableDictionary* _savedSystemCalendars;
	NSMutableDictionary* _savedSystemTimeZones;
	NSMutableDictionary* _savedDefaults;

}

@property (nonatomic,retain) _ORKTableContainerView * tableContainer;                 //@synthesize tableContainer=_tableContainer - In the implementation block
@property (nonatomic,retain) UITableView * tableView;                                 //@synthesize tableView=_tableView - In the implementation block
@property (nonatomic,retain) ORKStepHeaderView * headerView;                          //@synthesize headerView=_headerView - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * savedAnswers;                      //@synthesize savedAnswers=_savedAnswers - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * savedAnswerDates;                  //@synthesize savedAnswerDates=_savedAnswerDates - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * savedSystemCalendars;              //@synthesize savedSystemCalendars=_savedSystemCalendars - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * savedSystemTimeZones;              //@synthesize savedSystemTimeZones=_savedSystemTimeZones - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * savedDefaults;                     //@synthesize savedDefaults=_savedDefaults - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithStep:(id)arg1 ;
-(void)_stepDidChange;
-(void)skipForward;
-(void)setContinueButtonItem:(id)arg1 ;
-(void)setSkipButtonItem:(id)arg1 ;
-(id)initWithStep:(id)arg1 result:(id)arg2 ;
-(void)_showValidityAlertWithMessage:(id)arg1 ;
-(void)setLearnMoreButtonItem:(id)arg1 ;
-(id)_formItems;
-(void)formItemCell:(id)arg1 answerDidChangeTo:(id)arg2 ;
-(void)formItemCell:(id)arg1 invalidInputAlertWithMessage:(id)arg2 ;
-(void)formItemCellDidBecomeFirstResponder:(id)arg1 ;
-(void)_setAnswer:(id)arg1 forIdentifier:(id)arg2 ;
-(id)_ORKFormStepViewController_initWithResult:(id)arg1 ;
-(void)_refreshDefaults;
-(BOOL)_isSeparatorRow:(id)arg1 ;
-(BOOL)_isChoiceSelected:(id)arg1 atIndex:(unsigned long long)arg2 answer:(id)arg3 ;
-(void)_updateButtonStates;
-(void)_buildSections;
-(id)_formStep;
-(BOOL)continueButtonEnabled;
-(id)_allFormItems;
-(NSMutableDictionary *)savedAnswers;
-(long long)_numAnswered;
-(BOOL)_allAnswered;
-(void)_removeAnswerForIdentifier:(id)arg1 ;
-(BOOL)_isLastSection:(unsigned long long)arg1 ;
-(_ORKTableContainerView *)tableContainer;
-(void)setTableContainer:(_ORKTableContainerView *)arg1 ;
-(void)setSavedAnswers:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)savedAnswerDates;
-(void)setSavedAnswerDates:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)savedSystemCalendars;
-(void)setSavedSystemCalendars:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)savedSystemTimeZones;
-(void)setSavedSystemTimeZones:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)savedDefaults;
-(void)setSavedDefaults:(NSMutableDictionary *)arg1 ;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3 ;
-(double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2 ;
-(BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)decodeRestorableStateWithCoder:(id)arg1 ;
-(void)setTableView:(UITableView *)arg1 ;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(ORKStepHeaderView *)headerView;
-(void)setHeaderView:(ORKStepHeaderView *)arg1 ;
-(UITableView *)tableView;
-(id)result;
-(void)_updateDefaults:(id)arg1 ;
@end

