/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <UIKit/UIWebViewDelegate.h>

@class UIWebView, NSData, NSError, NSString;

@interface ORKHtmlPdfWriter : NSObject <UIWebViewDelegate> {

	id _selfRetain;
	UIWebView* _webView;
	NSData* _data;
	NSError* _error;
	/*^block*/id _completionBlock;
	CGSize _pageSize;
	UIEdgeInsets _pageMargins;

}

@property (assign,nonatomic) CGSize pageSize;                       //@synthesize pageSize=_pageSize - In the implementation block
@property (assign,nonatomic) UIEdgeInsets pageMargins;              //@synthesize pageMargins=_pageMargins - In the implementation block
@property (nonatomic,retain) UIWebView * webView;                   //@synthesize webView=_webView - In the implementation block
@property (nonatomic,retain) NSData * data;                         //@synthesize data=_data - In the implementation block
@property (nonatomic,retain) NSError * error;                       //@synthesize error=_error - In the implementation block
@property (nonatomic,copy) id completionBlock;                      //@synthesize completionBlock=_completionBlock - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(CGSize)defaultPageSize;
-(UIEdgeInsets)pageMargins;
-(void)setPageMargins:(UIEdgeInsets)arg1 ;
-(void)_savePdf;
-(void)_timeout;
-(void)writePdfFromHtml:(id)arg1 withCompletionBlock:(/*^block*/id)arg2 ;
-(NSData *)data;
-(void)setData:(NSData *)arg1 ;
-(UIWebView *)webView;
-(void)setWebView:(UIWebView *)arg1 ;
-(id)completionBlock;
-(void)setCompletionBlock:(id)arg1 ;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2 ;
-(void)webViewDidFinishLoad:(id)arg1 ;
-(void)setPageSize:(CGSize)arg1 ;
-(CGSize)pageSize;
-(NSError *)error;
-(void)setError:(NSError *)arg1 ;
@end

