/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKAnswerFormat.h>

@class ORKAnswerFormat, HKCharacteristicType;

@interface ORKHealthKitCharacteristicTypeAnswerFormat : ORKAnswerFormat {

	ORKAnswerFormat* _impliedAnswerFormat;
	HKCharacteristicType* _characteristicType;

}

@property (nonatomic,copy,readonly) HKCharacteristicType * characteristicType;              //@synthesize characteristicType=_characteristicType - In the implementation block
+(id)answerFormatWithCharacteristicType:(id)arg1 ;
-(id)dictionaryValue;
-(id)_impliedAnswerFormat;
-(id)initWithCharacteristicType:(id)arg1 ;
-(BOOL)_isHealthKitAnswerFormat;
-(id)_healthKitObjectType;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)initWithDictionary:(id)arg1 ;
-(HKCharacteristicType *)characteristicType;
@end

