/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <UIKit/UIPrintPageRenderer.h>

@interface ORKHtmlPdfPageRenderer : UIPrintPageRenderer {

	UIEdgeInsets _pageMargins;

}

@property (assign,nonatomic) UIEdgeInsets pageMargins;              //@synthesize pageMargins=_pageMargins - In the implementation block
-(UIEdgeInsets)pageMargins;
-(void)setPageMargins:(UIEdgeInsets)arg1 ;
-(CGRect)printableRect;
-(CGRect)paperRect;
-(void)drawFooterForPageAtIndex:(long long)arg1 inRect:(CGRect)arg2 ;
@end

