/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKLabel.h>

@interface ORKHeadlineLabel : ORKLabel {

	BOOL _useSurveyMode;

}

@property (assign,nonatomic) BOOL useSurveyMode;              //@synthesize useSurveyMode=_useSurveyMode - In the implementation block
+(id)defaultFontInSurveyMode:(BOOL)arg1 ;
+(id)defaultFont;
-(void)setUseSurveyMode:(BOOL)arg1 ;
-(BOOL)useSurveyMode;
-(id)_defaultFont;
-(unsigned long long)accessibilityTraits;
-(void)_updateAppearance;
@end

