/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKStep.h>

@class NSString, UIImage;

@interface ORKInstructionStep : ORKStep {

	NSString* _detailText;
	UIImage* _image;

}

@property (nonatomic,copy) NSString * detailText;              //@synthesize detailText=_detailText - In the implementation block
@property (nonatomic,copy) UIImage * image;                    //@synthesize image=_image - In the implementation block
+(Class)_stepViewControllerClass;
-(id)dictionaryValue;
-(NSString *)detailText;
-(void)setImage:(UIImage *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)initWithDictionary:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(UIImage *)image;
-(void)setDetailText:(NSString *)arg1 ;
@end

