/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:12 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKRecorder.h>
#import <ResearchKit/CLLocationManagerDelegate.h>

@class ORKDataLogger, NSError, CLLocationManager, NSString;

@interface ORKLocationRecorder : ORKRecorder <CLLocationManagerDelegate> {

	ORKDataLogger* _logger;
	NSError* _recordingError;
	BOOL _started;
	CLLocationManager* _locationManager;
	double _uptime;

}

@property (nonatomic,retain) CLLocationManager * locationManager;              //@synthesize locationManager=_locationManager - In the implementation block
@property (assign,nonatomic) double uptime;                                    //@synthesize uptime=_uptime - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithStep:(id)arg1 outputDirectory:(id)arg2 ;
-(void)finishRecordingWithError:(id)arg1 ;
-(void)setUptime:(double)arg1 ;
-(void)_doStopRecording;
-(id)_recorderType;
-(double)uptime;
-(BOOL)isRecording;
-(void)dealloc;
-(void)start;
-(id)mimeType;
-(void)_reset;
-(void)stop;
-(void)setLocationManager:(CLLocationManager *)arg1 ;
-(CLLocationManager *)locationManager;
-(void)locationManager:(id)arg1 didUpdateLocations:(id)arg2 ;
@end

