/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface ORKLogFormatter : NSObject {

	unsigned long long _checkpoint;

}
-(BOOL)canAcceptLogObject:(id)arg1 ;
-(BOOL)_writeData:(id)arg1 fileHandle:(id)arg2 error:(id*)arg3 ;
-(unsigned long long)_checkpointWithFileHandle:(id)arg1 ;
-(BOOL)appendObject:(id)arg1 fileHandle:(id)arg2 error:(id*)arg3 ;
-(void)_rollbackToCheckpoint:(unsigned long long)arg1 fileHandle:(id)arg2 ;
-(BOOL)canAcceptLogObjectOfClass:(Class)arg1 ;
-(BOOL)beginLogWithFileHandle:(id)arg1 error:(id*)arg2 ;
-(BOOL)appendObjects:(id)arg1 fileHandle:(id)arg2 error:(id*)arg3 ;
@end

