/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKAnswerFormat.h>

@class NSString, NSNumber;

@interface ORKNumericAnswerFormat : ORKAnswerFormat {

	long long _style;
	NSString* _unit;
	NSNumber* _minimum;
	NSNumber* _maximum;

}

@property (readonly) long long style;                   //@synthesize style=_style - In the implementation block
@property (copy,readonly) NSString * unit;              //@synthesize unit=_unit - In the implementation block
@property (copy) NSNumber * minimum;                    //@synthesize minimum=_minimum - In the implementation block
@property (copy) NSNumber * maximum;                    //@synthesize maximum=_maximum - In the implementation block
+(id)decimalAnswerFormatWithUnit:(id)arg1 ;
+(id)integerAnswerFormatWithUnit:(id)arg1 ;
+(Class)_questionResultClass;
-(id)dictionaryValue;
-(long long)questionType;
-(id)_makeNumberFormatter;
-(BOOL)_isAnswerValidWithString:(id)arg1 ;
-(id)_localizedInvalidValueStringWithAnswerString:(id)arg1 ;
-(id)_sanitizedTextFieldText:(id)arg1 decimalSeparator:(id)arg2 ;
-(id)initWithStyle:(long long)arg1 unit:(id)arg2 minimum:(id)arg3 maximum:(id)arg4 ;
-(id)initWithStyle:(long long)arg1 unit:(id)arg2 ;
-(id)_removeDecimalSeparatorsFromText:(id)arg1 numAllowed:(long long)arg2 separator:(id)arg3 ;
-(NSNumber *)minimum;
-(void)setMinimum:(NSNumber *)arg1 ;
-(NSNumber *)maximum;
-(void)setMaximum:(NSNumber *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)initWithDictionary:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(long long)style;
-(id)initWithStyle:(long long)arg1 ;
-(NSString *)unit;
@end

