/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKSerialization.h>
#import <ResearchKit/ORKTaskExtension.h>
#import <ResearchKit/ORKTask.h>
#import <ResearchKit/NSSecureCoding.h>
#import <ResearchKit/NSCopying.h>

@class NSString, NSSet, NSArray;

@interface ORKOrderedTask : NSObject <ORKSerialization, ORKTaskExtension, ORKTask, NSSecureCoding, NSCopying> {

	NSString* _identifier;
	NSArray* _steps;

}

@property (nonatomic,copy,readonly) NSArray * steps;                                        //@synthesize steps=_steps - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy,readonly) NSString * identifier; 
@property (nonatomic,copy,readonly) NSSet * requestedHealthKitTypesForReading; 
@property (nonatomic,readonly) BOOL providesBackgroundAudioPrompts; 
+(id)_makeCompletionStep;
+(id)_textTimeFormatter;
+(id)twoFingerTappingIntervalTaskWithIdentifier:(id)arg1 intendedUseDescription:(id)arg2 duration:(double)arg3 options:(unsigned long long)arg4 ;
+(id)audioTaskWithIdentifier:(id)arg1 intendedUseDescription:(id)arg2 speechInstruction:(id)arg3 shortSpeechInstruction:(id)arg4 duration:(double)arg5 recordingSettings:(id)arg6 options:(unsigned long long)arg7 ;
+(id)fitnessCheckTaskWithIdentifier:(id)arg1 intendedUseDescription:(id)arg2 walkDuration:(double)arg3 restDuration:(double)arg4 options:(unsigned long long)arg5 ;
+(id)shortWalkTaskWithIdentifier:(id)arg1 intendedUseDescription:(id)arg2 numberOfStepsPerLeg:(long long)arg3 restDuration:(double)arg4 options:(unsigned long long)arg5 ;
+(id)spatialSpanMemoryTaskWithIdentifier:(id)arg1 intendedUseDescription:(id)arg2 initialSpan:(long long)arg3 minimumSpan:(long long)arg4 maximumSpan:(long long)arg5 playSpeed:(double)arg6 maxTests:(long long)arg7 maxConsecutiveFailures:(long long)arg8 customTargetImage:(id)arg9 customTargetPluralName:(id)arg10 requireReversal:(BOOL)arg11 options:(unsigned long long)arg12 ;
+(BOOL)supportsSecureCoding;
-(id)dictionaryValue;
-(id)stepAfterStep:(id)arg1 withResult:(id)arg2 ;
-(id)stepBeforeStep:(id)arg1 withResult:(id)arg2 ;
-(id)stepWithIdentifier:(id)arg1 ;
-(ORKTaskProgress)progressOfCurrentStep:(id)arg1 withResult:(id)arg2 ;
-(NSSet *)requestedHealthKitTypesForReading;
-(long long)requestedPermissions;
-(id)requestedHealthKitTypesForWriting;
-(BOOL)providesBackgroundAudioPrompts;
-(unsigned long long)_indexOfStep:(id)arg1 ;
-(id)initWithIdentifier:(id)arg1 steps:(id)arg2 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)initWithDictionary:(id)arg1 ;
-(NSString *)identifier;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSArray *)steps;
@end

