/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKRecorder.h>

@class ORKDataLogger, NSDate, CMPedometer, NSError;

@interface ORKPedometerRecorder : ORKRecorder {

	ORKDataLogger* _logger;
	BOOL _isRecording;
	NSDate* _lastUpdateDate;
	long long _totalNumberOfSteps;
	long long _totalDistance;
	CMPedometer* _pedometer;
	NSError* _recordingError;

}

@property (nonatomic,readonly) NSDate * lastUpdateDate;                   //@synthesize lastUpdateDate=_lastUpdateDate - In the implementation block
@property (nonatomic,readonly) long long totalNumberOfSteps;              //@synthesize totalNumberOfSteps=_totalNumberOfSteps - In the implementation block
@property (nonatomic,readonly) long long totalDistance;                   //@synthesize totalDistance=_totalDistance - In the implementation block
@property (nonatomic,retain) CMPedometer * pedometer;                     //@synthesize pedometer=_pedometer - In the implementation block
@property (nonatomic,retain) NSError * recordingError;                    //@synthesize recordingError=_recordingError - In the implementation block
-(id)initWithStep:(id)arg1 outputDirectory:(id)arg2 ;
-(void)finishRecordingWithError:(id)arg1 ;
-(void)_doStopRecording;
-(id)_recorderType;
-(NSError *)recordingError;
-(void)setRecordingError:(NSError *)arg1 ;
-(long long)totalNumberOfSteps;
-(void)setPedometer:(CMPedometer *)arg1 ;
-(CMPedometer *)pedometer;
-(void)_updateStatisticsWithData:(id)arg1 ;
-(BOOL)isRecording;
-(void)dealloc;
-(long long)totalDistance;
-(void)start;
-(id)mimeType;
-(NSDate *)lastUpdateDate;
-(void)_reset;
-(void)stop;
@end

