/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKResult.h>

@interface ORKQuestionResult : ORKResult {

	long long _questionType;

}

@property (assign,nonatomic) long long questionType;              //@synthesize questionType=_questionType - In the implementation block
+(Class)answerClass;
-(long long)questionType;
-(id)_serializableDictionary;
-(void)setQuestionType:(long long)arg1 ;
-(id)_validateAnswer:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)isSaveable;
-(id)answer;
-(void)setAnswer:(id)arg1 ;
@end

