/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKStepViewController.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>
#import <ResearchKit/ORKSurveyAnswerCellDelegate.h>
#import <ResearchKit/ORKQuestionStepCustomViewDelegate.h>

@class _ORKTableContainerView, ORKStepHeaderView, ORKContinueSkipContainerView, ORKAnswerDefaultSource, NSCalendar, NSTimeZone, ORKQuestionStepCustomView, UITableView, ORKQuestionStepView, ORKAnswerFormat, ORKContinueButton, ORKSurveyAnswerCell, UILabel, NSString;

@interface ORKQuestionStepViewController : ORKStepViewController <UITableViewDataSource, UITableViewDelegate, ORKSurveyAnswerCellDelegate, ORKQuestionStepCustomViewDelegate> {

	id _answer;
	_ORKTableContainerView* _tableContainer;
	ORKStepHeaderView* _headerView;
	ORKContinueSkipContainerView* _continueSkipView;
	ORKAnswerDefaultSource* _defaultSource;
	NSCalendar* _savedSystemCalendar;
	NSTimeZone* _savedSystemTimeZone;
	id _defaultAnswer;
	BOOL _visible;
	BOOL _haveChangedAnswer;
	ORKQuestionStepCustomView* _customQuestionView;
	UITableView* _tableView;
	ORKQuestionStepView* _questionView;
	ORKAnswerFormat* _answerFormat;
	ORKContinueButton* _continueActionButton;
	ORKSurveyAnswerCell* _answerCell;
	UILabel* _questionLabel;
	UILabel* _promptLabel;

}

@property (nonatomic,retain) ORKQuestionStepCustomView * customQuestionView;              //@synthesize customQuestionView=_customQuestionView - In the implementation block
@property (nonatomic,retain) UITableView * tableView;                                     //@synthesize tableView=_tableView - In the implementation block
@property (nonatomic,retain) ORKQuestionStepView * questionView;                          //@synthesize questionView=_questionView - In the implementation block
@property (nonatomic,retain) ORKAnswerFormat * answerFormat;                              //@synthesize answerFormat=_answerFormat - In the implementation block
@property (nonatomic,copy) id<NSCopying><NSObject><NSCoding> answer; 
@property (nonatomic,retain) ORKContinueButton * continueActionButton;                    //@synthesize continueActionButton=_continueActionButton - In the implementation block
@property (nonatomic,retain) ORKSurveyAnswerCell * answerCell;                            //@synthesize answerCell=_answerCell - In the implementation block
@property (nonatomic,readonly) UILabel * questionLabel;                                   //@synthesize questionLabel=_questionLabel - In the implementation block
@property (nonatomic,readonly) UILabel * promptLabel;                                     //@synthesize promptLabel=_promptLabel - In the implementation block
@property (assign,nonatomic) BOOL haveChangedAnswer;                                      //@synthesize haveChangedAnswer=_haveChangedAnswer - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithStep:(id)arg1 ;
-(void)_stepDidChange;
-(void)goBackward;
-(void)skipForward;
-(void)_initializeInternalButtonItems;
-(void)setContinueButtonItem:(id)arg1 ;
-(void)setSkipButtonItem:(id)arg1 ;
-(id)initWithStep:(id)arg1 result:(id)arg2 ;
-(void)_notifyDelegateOnResultChange;
-(void)_showValidityAlertWithMessage:(id)arg1 ;
-(void)setLearnMoreButtonItem:(id)arg1 ;
-(ORKAnswerFormat *)answerFormat;
-(void)setHaveChangedAnswer:(BOOL)arg1 ;
-(BOOL)haveChangedAnswer;
-(void)_defaultAnswerDidChange;
-(void)_answerDidChange;
-(void)answerCell:(id)arg1 answerDidChangeTo:(id)arg2 ;
-(void)answerCell:(id)arg1 invalidInputAlertWithMessage:(id)arg2 ;
-(ORKContinueButton *)continueActionButton;
-(void)setContinueActionButton:(ORKContinueButton *)arg1 ;
-(void)setAnswerFormat:(ORKAnswerFormat *)arg1 ;
-(void)_refreshDefaults;
-(void)_updateButtonStates;
-(BOOL)continueButtonEnabled;
-(id)questionStep;
-(id)_answerCellForTableView:(id)arg1 ;
-(BOOL)allowContinue;
-(ORKSurveyAnswerCell *)answerCell;
-(BOOL)_hasAnswer;
-(void)saveAnswer:(id)arg1 ;
-(id)_choiceAnswerFormat;
-(void)setAnswerCell:(ORKSurveyAnswerCell *)arg1 ;
-(BOOL)_isChoiceSelected:(id)arg1 atIndex:(unsigned long long)arg2 ;
-(BOOL)_shouldContinue;
-(id)_selectedOption;
-(double)heightForChoiceItemOptionAtIndex:(long long)arg1 ;
-(void)customQuestionStepView:(id)arg1 didChangeAnswer:(id)arg2 ;
-(void)setCustomQuestionView:(ORKQuestionStepCustomView *)arg1 ;
-(ORKQuestionStepCustomView *)customQuestionView;
-(ORKQuestionStepView *)questionView;
-(void)setQuestionView:(ORKQuestionStepView *)arg1 ;
-(UILabel *)questionLabel;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3 ;
-(double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)decodeRestorableStateWithCoder:(id)arg1 ;
-(void)setTableView:(UITableView *)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(UITableView *)tableView;
-(void)goForward;
-(id)result;
-(void)_continueAction:(id)arg1 ;
-(id<NSCopying><NSObject><NSCoding>)answer;
-(void)setAnswer:(id<NSCopying><NSObject><NSCoding>)arg1 ;
-(UILabel *)promptLabel;
@end

