/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKQuestionStepCustomView.h>

@class ORKSurveyAnswerCell;

@interface ORKQuestionStepCellHolderView : ORKQuestionStepCustomView {

	ORKSurveyAnswerCell* _cell;

}

@property (nonatomic,retain) ORKSurveyAnswerCell * cell;              //@synthesize cell=_cell - In the implementation block
-(void)_tapAction;
-(id)initWithFrame:(CGRect)arg1 ;
-(ORKSurveyAnswerCell *)cell;
-(void)setCell:(ORKSurveyAnswerCell *)arg1 ;
@end

