/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@protocol ORKQuestionStepCustomViewDelegate;
@interface ORKQuestionStepCustomView : UIView {

	id<ORKQuestionStepCustomViewDelegate> _delegate;
	id _answer;

}

@property (assign,nonatomic,__weak) id<ORKQuestionStepCustomViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) id answer;                                                            //@synthesize answer=_answer - In the implementation block
-(void)setDelegate:(id<ORKQuestionStepCustomViewDelegate>)arg1 ;
-(id<ORKQuestionStepCustomViewDelegate>)delegate;
-(id)answer;
-(void)setAnswer:(id)arg1 ;
@end

