/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <UIKit/UISlider.h>

@interface ORKScaleSlider : UISlider {

	double _axLastOutputTime;
	BOOL _showThumb;
	unsigned long long _numberOfSteps;

}

@property (assign,nonatomic) BOOL showThumb;                                //@synthesize showThumb=_showThumb - In the implementation block
@property (assign,nonatomic) unsigned long long numberOfSteps;              //@synthesize numberOfSteps=_numberOfSteps - In the implementation block
-(void)sliderTouched:(id)arg1 ;
-(void)setShowThumb:(BOOL)arg1 ;
-(void)updateValueForTouchAtPoint:(CGPoint)arg1 ;
-(void)announceNewValue;
-(void)_axBumpValue:(BOOL)arg1 ;
-(BOOL)showThumb;
-(void)setNumberOfSteps:(unsigned long long)arg1 ;
-(unsigned long long)numberOfSteps;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(id)accessibilityLabel;
-(CGRect)trackRectForBounds:(CGRect)arg1 ;
-(CGRect)thumbRectForBounds:(CGRect)arg1 trackRect:(CGRect)arg2 value:(float)arg3 ;
-(CGRect)accessibilityFrame;
-(id)accessibilityValue;
-(BOOL)isAccessibilityElement;
-(void)accessibilityIncrement;
-(void)accessibilityDecrement;
@end

