/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKSurveyAnswerCell.h>
#import <UIKit/UITextViewDelegate.h>

@class NSArray, ORKAnswerTextView, UILabel, NSString;

@interface ORKSurveyAnswerCellForText : ORKSurveyAnswerCell <UITextViewDelegate> {

	long long _maxLength;
	NSArray* _constraints;
	ORKAnswerTextView* _textView;
	UILabel* _placeHolder;

}

@property (nonatomic,retain) ORKAnswerTextView * textView;              //@synthesize textView=_textView - In the implementation block
@property (nonatomic,retain) UILabel * placeHolder;                     //@synthesize placeHolder=_placeHolder - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)_shouldDisplayWithSeparators;
+(double)suggestedCellHeightForView:(id)arg1 ;
-(void)_answerDidChange;
-(void)_applyAnswerFormat;
-(void)prepareView;
-(id)initWithFrame:(CGRect)arg1 ;
-(BOOL)becomeFirstResponder;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)setTextView:(ORKAnswerTextView *)arg1 ;
-(void)updateConstraints;
-(void)textViewDidBeginEditing:(id)arg1 ;
-(void)textViewDidEndEditing:(id)arg1 ;
-(BOOL)textView:(id)arg1 shouldChangeTextInRange:(NSRange)arg2 replacementText:(id)arg3 ;
-(void)textViewDidChange:(id)arg1 ;
-(void)_textDidChange;
-(ORKAnswerTextView *)textView;
-(UILabel *)placeHolder;
-(void)setPlaceHolder:(UILabel *)arg1 ;
-(void)setStep:(id)arg1 ;
@end

