/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKTableViewCell.h>

@protocol ORKSurveyAnswerCellDelegate;
@class ORKQuestionStep;

@interface ORKSurveyAnswerCell : ORKTableViewCell {

	id _answer;
	ORKQuestionStep* _step;
	id<ORKSurveyAnswerCellDelegate> _delegate;
	UIEdgeInsets _cachedContentInsets;
	UIEdgeInsets _cachedScrollIndicatorInsets;

}

@property (assign,nonatomic,__weak) ORKQuestionStep * step;                                //@synthesize step=_step - In the implementation block
@property (assign,nonatomic,__weak) id<ORKSurveyAnswerCellDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) id answer;                                                      //@synthesize answer=_answer - In the implementation block
@property (assign,nonatomic) UIEdgeInsets cachedContentInsets;                             //@synthesize cachedContentInsets=_cachedContentInsets - In the implementation block
@property (assign,nonatomic) UIEdgeInsets cachedScrollIndicatorInsets;                     //@synthesize cachedScrollIndicatorInsets=_cachedScrollIndicatorInsets - In the implementation block
+(BOOL)_shouldDisplayWithSeparators;
+(double)suggestedCellHeightForView:(id)arg1 ;
-(void)_showValidityAlertWithMessage:(id)arg1 ;
-(void)_setAnswer:(id)arg1 ;
-(void)_answerDidChange;
-(BOOL)shouldContinue;
-(void)registerForKeyboardNotifications;
-(void)keyboardWillAppear:(id)arg1 ;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 step:(id)arg3 answer:(id)arg4 delegate:(id)arg5 ;
-(id)suggestedCellHeightConstraintsForView:(id)arg1 ;
-(UIEdgeInsets)cachedContentInsets;
-(void)setCachedContentInsets:(UIEdgeInsets)arg1 ;
-(UIEdgeInsets)cachedScrollIndicatorInsets;
-(void)setCachedScrollIndicatorInsets:(UIEdgeInsets)arg1 ;
-(void)prepareView;
-(void)dealloc;
-(void)setDelegate:(id<ORKSurveyAnswerCellDelegate>)arg1 ;
-(void)layoutSubviews;
-(id<ORKSurveyAnswerCellDelegate>)delegate;
-(id)textField;
-(id)textView;
-(id)answer;
-(void)setAnswer:(id)arg1 ;
-(void)keyboardWillHide:(id)arg1 ;
-(ORKQuestionStep *)step;
-(void)setStep:(ORKQuestionStep *)arg1 ;
@end

