/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <UIKit/UIView.h>

@class NSDictionary, NSArray, UIBarButtonItem, ORKHeadlineLabel, ORKTextButton, ORKSubheadlineLabel;

@interface ORKStepHeaderView : UIView {

	NSDictionary* _adjustableConstraints;
	NSArray* _myConstraints;
	long long _screenType;
	BOOL _hasContentAbove;
	UIBarButtonItem* _learnMoreButtonItem;
	ORKHeadlineLabel* _captionLabel;
	ORKTextButton* _learnMoreButton;
	ORKSubheadlineLabel* _instructionLabel;

}

@property (nonatomic,retain) UIBarButtonItem * learnMoreButtonItem;               //@synthesize learnMoreButtonItem=_learnMoreButtonItem - In the implementation block
@property (nonatomic,retain) ORKHeadlineLabel * captionLabel;                     //@synthesize captionLabel=_captionLabel - In the implementation block
@property (nonatomic,retain) ORKTextButton * learnMoreButton;                     //@synthesize learnMoreButton=_learnMoreButton - In the implementation block
@property (nonatomic,retain) ORKSubheadlineLabel * instructionLabel;              //@synthesize instructionLabel=_instructionLabel - In the implementation block
@property (assign,nonatomic) BOOL hasContentAbove;                                //@synthesize hasContentAbove=_hasContentAbove - In the implementation block
-(UIBarButtonItem *)learnMoreButtonItem;
-(void)setLearnMoreButtonItem:(UIBarButtonItem *)arg1 ;
-(ORKSubheadlineLabel *)instructionLabel;
-(void)_updateConstraintConstants;
-(void)setHasContentAbove:(BOOL)arg1 ;
-(void)_updateCaptionLabelPreferredWidth;
-(void)setLearnMoreButton:(ORKTextButton *)arg1 ;
-(void)setInstructionLabel:(ORKSubheadlineLabel *)arg1 ;
-(BOOL)hasContentAbove;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setBounds:(CGRect)arg1 ;
-(void)setLayoutMargins:(UIEdgeInsets)arg1 ;
-(void)willMoveToWindow:(id)arg1 ;
-(void)updateConstraints;
-(ORKTextButton *)learnMoreButton;
-(ORKHeadlineLabel *)captionLabel;
-(void)setCaptionLabel:(ORKHeadlineLabel *)arg1 ;
-(void)_learnMoreAction:(id)arg1 ;
@end

