/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKSurveyAnswerCell.h>
#import <UIKit/UITextFieldDelegate.h>

@class NSNumberFormatter, UIView, _ORKTextFieldView, NSString;

@interface ORKSurveyAnswerCellForNumber : ORKSurveyAnswerCell <UITextFieldDelegate> {

	NSNumberFormatter* _numberFormatter;
	UIView* _containerView;
	_ORKTextFieldView* _textFieldView;

}

@property (nonatomic,retain) UIView * containerView;                         //@synthesize containerView=_containerView - In the implementation block
@property (nonatomic,retain) _ORKTextFieldView * textFieldView;              //@synthesize textFieldView=_textFieldView - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)_shouldDisplayWithSeparators;
-(void)_answerDidChange;
-(void)_valueFieldDidChange:(id)arg1 ;
-(void)_setAnswerWithText:(id)arg1 ;
-(BOOL)_isAnswerValid;
-(BOOL)shouldContinue;
-(void)_numberCell_initialize;
-(void)prepareView;
-(void)dealloc;
-(UIView *)containerView;
-(BOOL)becomeFirstResponder;
-(void)setContainerView:(UIView *)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(BOOL)textFieldShouldEndEditing:(id)arg1 ;
-(void)textFieldDidEndEditing:(id)arg1 ;
-(BOOL)textFieldShouldClear:(id)arg1 ;
-(BOOL)textFieldShouldReturn:(id)arg1 ;
-(void)updateConstraints;
-(void)setNeedsUpdateConstraints;
-(id)textField;
-(_ORKTextFieldView *)textFieldView;
-(void)setTextFieldView:(_ORKTextFieldView *)arg1 ;
-(void)_localeDidChange:(id)arg1 ;
@end

