/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:12 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UIViewControllerRestoration.h>

@protocol ORKStepViewControllerDelegate;
@class ORKStep, UIBarButtonItem, NSURL, NSDate, NSString, ORKStepResult, ORKTaskViewController;

@interface ORKStepViewController : UIViewController <UIViewControllerRestoration> {

	BOOL _hasBeenPresented;
	BOOL _dismissing;
	BOOL _presentingAlert;
	ORKStep* _step;
	id<ORKStepViewControllerDelegate> _delegate;
	UIBarButtonItem* _backButtonItem;
	UIBarButtonItem* _cancelButtonItem;
	NSURL* _outputDirectory;
	UIBarButtonItem* _internalContinueButtonItem;
	UIBarButtonItem* _internalBackButtonItem;
	UIBarButtonItem* _internalDoneButtonItem;
	UIBarButtonItem* _internalSkipButtonItem;
	UIBarButtonItem* _continueButtonItem;
	UIBarButtonItem* _learnMoreButtonItem;
	UIBarButtonItem* _skipButtonItem;
	NSDate* _presentedDate;
	NSDate* _dismissedDate;
	NSString* _restoredStepIdentifier;
	UIBarButtonItem* _flexSpace;
	UIBarButtonItem* _fixedSpace;

}

@property (nonatomic,retain) ORKStep * step;                                                 //@synthesize step=_step - In the implementation block
@property (assign,nonatomic,__weak) id<ORKStepViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSString * continueButtonTitle; 
@property (nonatomic,copy) NSString * learnMoreButtonTitle; 
@property (nonatomic,copy) NSString * skipButtonTitle; 
@property (nonatomic,retain) UIBarButtonItem * backButtonItem;                               //@synthesize backButtonItem=_backButtonItem - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * cancelButtonItem;                             //@synthesize cancelButtonItem=_cancelButtonItem - In the implementation block
@property (nonatomic,copy,readonly) ORKStepResult * result; 
@property (nonatomic,readonly) ORKTaskViewController * taskViewController; 
@property (nonatomic,copy) NSURL * outputDirectory;                                          //@synthesize outputDirectory=_outputDirectory - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * internalContinueButtonItem;                   //@synthesize internalContinueButtonItem=_internalContinueButtonItem - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * internalBackButtonItem;                       //@synthesize internalBackButtonItem=_internalBackButtonItem - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * internalDoneButtonItem;                       //@synthesize internalDoneButtonItem=_internalDoneButtonItem - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * internalSkipButtonItem;                       //@synthesize internalSkipButtonItem=_internalSkipButtonItem - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * continueButtonItem;                           //@synthesize continueButtonItem=_continueButtonItem - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * learnMoreButtonItem;                          //@synthesize learnMoreButtonItem=_learnMoreButtonItem - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * skipButtonItem;                               //@synthesize skipButtonItem=_skipButtonItem - In the implementation block
@property (nonatomic,copy) NSDate * presentedDate;                                           //@synthesize presentedDate=_presentedDate - In the implementation block
@property (nonatomic,copy) NSDate * dismissedDate;                                           //@synthesize dismissedDate=_dismissedDate - In the implementation block
@property (nonatomic,copy) NSString * restoredStepIdentifier;                                //@synthesize restoredStepIdentifier=_restoredStepIdentifier - In the implementation block
@property (nonatomic,readonly) UIBarButtonItem * flexSpace;                                  //@synthesize flexSpace=_flexSpace - In the implementation block
@property (nonatomic,readonly) UIBarButtonItem * fixedSpace;                                 //@synthesize fixedSpace=_fixedSpace - In the implementation block
+(id)viewControllerWithRestorationIdentifierPath:(id)arg1 coder:(id)arg2 ;
-(id)initWithStep:(id)arg1 ;
-(void)_stepDidChange;
-(void)goBackward;
-(void)skipForward;
-(void)_initializeInternalButtonItems;
-(BOOL)hasPreviousStep;
-(void)_setBackButtonItem:(id)arg1 ;
-(BOOL)hasNextStep;
-(void)setContinueButtonItem:(UIBarButtonItem *)arg1 ;
-(void)setSkipButtonItem:(UIBarButtonItem *)arg1 ;
-(NSDate *)presentedDate;
-(void)setPresentedDate:(NSDate *)arg1 ;
-(void)setDismissedDate:(NSDate *)arg1 ;
-(UIBarButtonItem *)internalContinueButtonItem;
-(UIBarButtonItem *)internalDoneButtonItem;
-(UIBarButtonItem *)continueButtonItem;
-(UIBarButtonItem *)learnMoreButtonItem;
-(UIBarButtonItem *)internalSkipButtonItem;
-(UIBarButtonItem *)skipButtonItem;
-(void)_updateNavLeftBarButtonItem;
-(void)_updateNavRightBarButtonItem;
-(NSDate *)dismissedDate;
-(void)setOutputDirectory:(NSURL *)arg1 ;
-(void)setRestoredStepIdentifier:(NSString *)arg1 ;
-(id)initWithStep:(id)arg1 result:(id)arg2 ;
-(void)_willNavigateDirection:(long long)arg1 ;
-(void)setLearnMoreButtonTitle:(NSString *)arg1 ;
-(NSString *)learnMoreButtonTitle;
-(void)setSkipButtonTitle:(NSString *)arg1 ;
-(NSString *)skipButtonTitle;
-(void)setBackButtonItem:(UIBarButtonItem *)arg1 ;
-(void)_notifyDelegateOnResultChange;
-(ORKTaskViewController *)taskViewController;
-(void)_showValidityAlertWithMessage:(id)arg1 ;
-(UIBarButtonItem *)backButtonItem;
-(NSURL *)outputDirectory;
-(void)setInternalContinueButtonItem:(UIBarButtonItem *)arg1 ;
-(UIBarButtonItem *)internalBackButtonItem;
-(void)setInternalBackButtonItem:(UIBarButtonItem *)arg1 ;
-(void)setInternalDoneButtonItem:(UIBarButtonItem *)arg1 ;
-(void)setInternalSkipButtonItem:(UIBarButtonItem *)arg1 ;
-(void)setLearnMoreButtonItem:(UIBarButtonItem *)arg1 ;
-(NSString *)restoredStepIdentifier;
-(UIBarButtonItem *)flexSpace;
-(UIBarButtonItem *)fixedSpace;
-(void)_setupButtons;
-(id)initWithCoder:(id)arg1 ;
-(void)setDelegate:(id<ORKStepViewControllerDelegate>)arg1 ;
-(id<ORKStepViewControllerDelegate>)delegate;
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)decodeRestorableStateWithCoder:(id)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)goForward;
-(ORKStepResult *)result;
-(void)setContinueButtonTitle:(NSString *)arg1 ;
-(NSString *)continueButtonTitle;
-(UIBarButtonItem *)cancelButtonItem;
-(void)setCancelButtonItem:(UIBarButtonItem *)arg1 ;
-(ORKStep *)step;
-(void)setStep:(ORKStep *)arg1 ;
@end

