/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKSurveyAnswerCell.h>
#import <UIKit/UIPickerViewDelegate.h>

@class UIPickerView, UIDatePicker, NSString;

@interface ORKSurveyAnswerCellForDateTime : ORKSurveyAnswerCell <UIPickerViewDelegate> {

	UIPickerView* _tempPicker;
	BOOL _valueChangedDueUserAction;
	UIDatePicker* _picker;

}

@property (nonatomic,retain) UIDatePicker * picker;                 //@synthesize picker=_picker - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(double)suggestedCellHeightForView:(id)arg1 ;
+(id)datePickerForStep:(id)arg1 ;
-(id)_impliedAnswerFormat;
-(void)_setAnswer:(id)arg1 ;
-(void)_answerDidChange;
-(void)_restoreValue:(id)arg1 ;
-(void)_valueChangedDueUserAction:(BOOL)arg1 ;
-(void)_setupPicker;
-(id)_dateAnswerFormat;
-(id)_timeOfDayAnswerFormat;
-(void)loadDatePicker;
-(void)prepareView;
-(void)dealloc;
-(double)pickerView:(id)arg1 rowHeightForComponent:(long long)arg2 ;
-(void)layoutSubviews;
-(void)valueChanged:(id)arg1 ;
-(UIDatePicker *)picker;
-(void)setPicker:(UIDatePicker *)arg1 ;
@end

