/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <UIKit/UIView.h>
#import <ResearchKit/ORKSignatureGestureRecognizerDelegate.h>

@protocol ORKSignatureViewDelegate;
@class UIColor, UIGestureRecognizer, UIBezierPath, NSMutableArray, NSArray, NSString;

@interface ORKSignatureView : UIView <ORKSignatureGestureRecognizerDelegate> {

	CGPoint currentPoint;
	CGPoint previousPoint1;
	CGPoint previousPoint2;
	UIColor* _lineColor;
	double _lineWidth;
	id<ORKSignatureViewDelegate> _delegate;
	UIGestureRecognizer* _signatureGestureRecognizer;
	UIBezierPath* _currentPath;
	NSMutableArray* _pathArray;
	NSArray* _backgroundLines;

}

@property (nonatomic,retain) UIColor * lineColor;                                           //@synthesize lineColor=_lineColor - In the implementation block
@property (assign,nonatomic) double lineWidth;                                              //@synthesize lineWidth=_lineWidth - In the implementation block
@property (assign,nonatomic,__weak) id<ORKSignatureViewDelegate> delegate;                  //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UIGestureRecognizer * signatureGestureRecognizer;              //@synthesize signatureGestureRecognizer=_signatureGestureRecognizer - In the implementation block
@property (nonatomic,retain) UIBezierPath * currentPath;                                    //@synthesize currentPath=_currentPath - In the implementation block
@property (nonatomic,retain) NSMutableArray * pathArray;                                    //@synthesize pathArray=_pathArray - In the implementation block
@property (nonatomic,retain) NSArray * backgroundLines;                                     //@synthesize backgroundLines=_backgroundLines - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)initialize;
-(BOOL)signatureExists;
-(void)gestureTouchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)gestureTouchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)gestureTouchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)makeSignatureGestureRecognizer;
-(id)pathWithRoundedStyle;
-(NSMutableArray *)pathArray;
-(NSArray *)backgroundLines;
-(CGPoint)placeholderPoint;
-(id)signatureImage;
-(UIGestureRecognizer *)signatureGestureRecognizer;
-(void)setSignatureGestureRecognizer:(UIGestureRecognizer *)arg1 ;
-(void)setPathArray:(NSMutableArray *)arg1 ;
-(void)setBackgroundLines:(NSArray *)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(void)setDelegate:(id<ORKSignatureViewDelegate>)arg1 ;
-(id)init;
-(id<ORKSignatureViewDelegate>)delegate;
-(double)lineWidth;
-(void)setLineWidth:(double)arg1 ;
-(id)accessibilityLabel;
-(id)accessibilityValue;
-(id)accessibilityHint;
-(unsigned long long)accessibilityTraits;
-(BOOL)isAccessibilityElement;
-(BOOL)clear;
-(UIBezierPath *)currentPath;
-(void)setCurrentPath:(UIBezierPath *)arg1 ;
-(UIColor *)lineColor;
-(void)setLineColor:(UIColor *)arg1 ;
@end

