/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKSurveyAnswerCell.h>
#import <UIKit/UITextFieldDelegate.h>

@class ORKAnswerTextField, NSString;

@interface ORKSurveyAnswerCellForTextField : ORKSurveyAnswerCell <UITextFieldDelegate> {

	ORKAnswerTextField* _textField;

}

@property (nonatomic,retain) ORKAnswerTextField * textField;              //@synthesize textField=_textField - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)_shouldDisplayWithSeparators;
-(void)_answerDidChange;
-(void)_textFieldCell_initialize;
-(BOOL)_correctValueIfNeeded;
-(BOOL)_correctionNeededForText:(id)arg1 ;
-(BOOL)shouldContinue;
-(void)prepareView;
-(BOOL)becomeFirstResponder;
-(void)traitCollectionDidChange:(id)arg1 ;
-(BOOL)textFieldShouldEndEditing:(id)arg1 ;
-(void)textFieldDidEndEditing:(id)arg1 ;
-(BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(NSRange)arg2 replacementString:(id)arg3 ;
-(BOOL)textFieldShouldReturn:(id)arg1 ;
-(void)updateConstraints;
-(ORKAnswerTextField *)textField;
-(void)setTextField:(ORKAnswerTextField *)arg1 ;
@end

