/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKSurveyAnswerCell.h>

@protocol _ORKScaleAnswerFormatProvider;
@class ORKScaleSlider, ORKScaleRangeLabel, ORKScaleValueLabel;

@interface ORKSurveyAnswerCellForScale : ORKSurveyAnswerCell {

	ORKScaleSlider* _slider;
	ORKScaleRangeLabel* _leftTextLabel;
	ORKScaleRangeLabel* _rightTextLabel;
	ORKScaleValueLabel* _currentValueLabel;
	id<_ORKScaleAnswerFormatProvider> _formatProvider;

}

@property (nonatomic,retain) ORKScaleSlider * slider;                                       //@synthesize slider=_slider - In the implementation block
@property (nonatomic,retain) ORKScaleRangeLabel * leftTextLabel;                            //@synthesize leftTextLabel=_leftTextLabel - In the implementation block
@property (nonatomic,retain) ORKScaleRangeLabel * rightTextLabel;                           //@synthesize rightTextLabel=_rightTextLabel - In the implementation block
@property (nonatomic,retain) ORKScaleValueLabel * currentValueLabel;                        //@synthesize currentValueLabel=_currentValueLabel - In the implementation block
@property (nonatomic,retain) id<_ORKScaleAnswerFormatProvider> formatProvider;              //@synthesize formatProvider=_formatProvider - In the implementation block
+(double)suggestedCellHeightForView:(id)arg1 ;
-(void)_answerDidChange;
-(id<_ORKScaleAnswerFormatProvider>)formatProvider;
-(ORKScaleRangeLabel *)leftTextLabel;
-(void)setLeftTextLabel:(ORKScaleRangeLabel *)arg1 ;
-(ORKScaleRangeLabel *)rightTextLabel;
-(void)setRightTextLabel:(ORKScaleRangeLabel *)arg1 ;
-(void)sliderValueChanged:(id)arg1 ;
-(ORKScaleValueLabel *)currentValueLabel;
-(void)setCurrentValueLabel:(ORKScaleValueLabel *)arg1 ;
-(void)setFormatProvider:(id<_ORKScaleAnswerFormatProvider>)arg1 ;
-(void)prepareView;
-(void)setSlider:(ORKScaleSlider *)arg1 ;
-(ORKScaleSlider *)slider;
-(void)updateConstraints;
-(BOOL)isAccessibilityElement;
-(long long)accessibilityElementCount;
-(id)accessibilityElementAtIndex:(long long)arg1 ;
-(long long)indexOfAccessibilityElement:(id)arg1 ;
@end

