/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIGestureRecognizer.h>

@protocol ORKSignatureGestureRecognizerDelegate;
@interface ORKSignatureGestureRecognizer : UIGestureRecognizer {

	id<ORKSignatureGestureRecognizerDelegate> _eventDelegate;

}

@property (assign,nonatomic,__weak) id<ORKSignatureGestureRecognizerDelegate> eventDelegate;              //@synthesize eventDelegate=_eventDelegate - In the implementation block
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(BOOL)shouldRequireFailureOfGestureRecognizer:(id)arg1 ;
-(void)setEventDelegate:(id<ORKSignatureGestureRecognizerDelegate>)arg1 ;
-(id<ORKSignatureGestureRecognizerDelegate>)eventDelegate;
@end

