/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKAnswerFormat.h>
#import <ResearchKit/_ORKScaleAnswerFormatProvider.h>

@class NSString;

@interface ORKScaleAnswerFormat : ORKAnswerFormat <_ORKScaleAnswerFormatProvider> {

	long long _maximum;
	long long _minimum;
	long long _step;
	long long _defaultValue;

}

@property (readonly) long long maximum;                             //@synthesize maximum=_maximum - In the implementation block
@property (readonly) long long minimum;                             //@synthesize minimum=_minimum - In the implementation block
@property (readonly) long long step;                                //@synthesize step=_step - In the implementation block
@property (readonly) long long defaultValue;                        //@synthesize defaultValue=_defaultValue - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(Class)_questionResultClass;
-(id)dictionaryValue;
-(void)validateParameters;
-(long long)questionType;
-(long long)_numberOfSteps;
-(id)_minimumNumber;
-(id)_localizedStringForNumber:(id)arg1 ;
-(id)_maximumNumber;
-(id)_normalizedValueForNumber:(id)arg1 ;
-(id)_defaultNumber;
-(id)initWithMaximumValue:(long long)arg1 minimumValue:(long long)arg2 step:(long long)arg3 defaultValue:(long long)arg4 ;
-(long long)minimum;
-(long long)maximum;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)initWithDictionary:(id)arg1 ;
-(long long)step;
-(long long)defaultValue;
@end

