/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ORKStepViewControllerDelegate <NSObject>
@optional
-(void)stepViewControllerWillAppear:(id)arg1;
-(BOOL)stepViewControllerHasPreviousStep:(id)arg1;
-(BOOL)stepViewControllerHasNextStep:(id)arg1;

@required
-(void)stepViewControllerResultDidChange:(id)arg1;
-(void)stepViewController:(id)arg1 didFinishWithNavigationDirection:(long long)arg2;
-(void)stepViewControllerDidFail:(id)arg1 withError:(id)arg2;

@end

