/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:14 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/NSCopying.h>
#import <ResearchKit/NSSecureCoding.h>

@class NSArray;

@interface ORKSpatialSpanMemoryGameRecord : NSObject <NSCopying, NSSecureCoding> {

	unsigned _seed;
	NSArray* _sequence;
	long long _gameSize;
	NSArray* _targetRects;
	NSArray* _touchSamples;
	long long _gameStatus;
	long long _score;

}

@property (assign,nonatomic) unsigned seed;                     //@synthesize seed=_seed - In the implementation block
@property (nonatomic,copy) NSArray * sequence;                  //@synthesize sequence=_sequence - In the implementation block
@property (assign,nonatomic) long long gameSize;                //@synthesize gameSize=_gameSize - In the implementation block
@property (nonatomic,copy) NSArray * targetRects;               //@synthesize targetRects=_targetRects - In the implementation block
@property (nonatomic,copy) NSArray * touchSamples;              //@synthesize touchSamples=_touchSamples - In the implementation block
@property (assign,nonatomic) long long gameStatus;              //@synthesize gameStatus=_gameStatus - In the implementation block
@property (assign,nonatomic) long long score;                   //@synthesize score=_score - In the implementation block
+(BOOL)supportsSecureCoding;
-(long long)gameSize;
-(long long)gameStatus;
-(void)setGameSize:(long long)arg1 ;
-(void)setTargetRects:(NSArray *)arg1 ;
-(NSArray *)touchSamples;
-(void)setTouchSamples:(NSArray *)arg1 ;
-(void)setGameStatus:(long long)arg1 ;
-(NSArray *)targetRects;
-(NSArray *)sequence;
-(void)setSequence:(NSArray *)arg1 ;
-(void)setSeed:(unsigned)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(unsigned)seed;
-(long long)score;
-(void)setScore:(long long)arg1 ;
@end

