/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKSerialization.h>
#import <ResearchKit/NSSecureCoding.h>
#import <ResearchKit/NSCopying.h>

@protocol ORKTask;
@class NSString;

@interface ORKStep : NSObject <ORKSerialization, NSSecureCoding, NSCopying> {

	BOOL _optional;
	BOOL _shouldTintImages;
	BOOL _useSurveyMode;
	NSString* _identifier;
	NSString* _title;
	NSString* _text;
	id<ORKTask> _task;

}

@property (nonatomic,copy,readonly) NSString * identifier;                       //@synthesize identifier=_identifier - In the implementation block
@property (getter=isRestorable,nonatomic,readonly) BOOL restorable; 
@property (assign,getter=isOptional,nonatomic) BOOL optional;                    //@synthesize optional=_optional - In the implementation block
@property (nonatomic,copy) NSString * title;                                     //@synthesize title=_title - In the implementation block
@property (nonatomic,copy) NSString * text;                                      //@synthesize text=_text - In the implementation block
@property (assign,nonatomic,__weak) id<ORKTask> task;                            //@synthesize task=_task - In the implementation block
@property (assign,nonatomic) BOOL shouldTintImages;                              //@synthesize shouldTintImages=_shouldTintImages - In the implementation block
@property (assign,nonatomic) BOOL useSurveyMode;                                 //@synthesize useSurveyMode=_useSurveyMode - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(Class)_stepViewControllerClass;
+(BOOL)supportsSecureCoding;
-(id)dictionaryValue;
-(BOOL)_shouldShowProgress;
-(void)validateParameters;
-(void)setUseSurveyMode:(BOOL)arg1 ;
-(BOOL)isRestorable;
-(BOOL)_shouldAllowBackNavigation;
-(void)setShouldTintImages:(BOOL)arg1 ;
-(BOOL)shouldTintImages;
-(BOOL)useSurveyMode;
-(void)setTask:(id<ORKTask>)arg1 ;
-(BOOL)isOptional;
-(void)setOptional:(BOOL)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(id)initWithDictionary:(id)arg1 ;
-(NSString *)identifier;
-(NSString *)title;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
-(id)initWithIdentifier:(id)arg1 ;
-(id<ORKTask>)task;
@end

