/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <ResearchKit/ORKStepViewControllerDelegate.h>
#import <UIKit/UIViewControllerRestoration.h>

@protocol ORKTaskViewControllerDelegate, ORKTask, ORKTaskResultSource;
@class NSMutableDictionary, NSMutableArray, _ORKTaskViewControllerObserver, _ORKScrollViewObserver, NSSet, NSURL, NSDate, NSString, NSUUID, ORKStepViewController, UIScrollView, UIImageView, UINavigationController, UIPageViewController, ORKTaskResult, NSData, UINavigationBar;

@interface ORKTaskViewController : UIViewController <ORKStepViewControllerDelegate, UIViewControllerRestoration> {

	NSMutableDictionary* _managedResults;
	NSMutableArray* _managedStepIdentifiers;
	_ORKTaskViewControllerObserver* _stepVCObserver;
	_ORKScrollViewObserver* _scrollViewObserver;
	BOOL _haveSetProgressLabel;
	BOOL _hasBeenPresented;
	BOOL _hasRequestedHealthData;
	long long _grantedPermissions;
	NSSet* _requestedHealthTypesForRead;
	NSSet* _requestedHealthTypesForWrite;
	NSURL* _outputDirectory;
	NSDate* _presentedDate;
	NSDate* _dismissedDate;
	NSString* _lastBeginningInstructionStepIdentifier;
	NSString* _lastRestorableStepIdentifier;
	BOOL _haveAudioSession;
	NSString* _restoredTaskIdentifier;
	NSString* _restoredStepIdentifier;
	BOOL _showsProgressInNavigationBar;
	NSUUID* _taskRunUUID;
	id<ORKTaskViewControllerDelegate> _delegate;
	id<ORKTask> _task;
	id<ORKTaskResultSource> _defaultResultSource;
	ORKStepViewController* _currentStepViewController;
	UIScrollView* _registeredScrollView;
	UIImageView* _hairline;
	UINavigationController* _childNavigationController;
	UIPageViewController* _pageViewController;

}

@property (assign,nonatomic,__weak) id<ORKTaskViewControllerDelegate> delegate;                  //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) id<ORKTask> task;                                                   //@synthesize task=_task - In the implementation block
@property (nonatomic,retain) id<ORKTaskResultSource> defaultResultSource;                        //@synthesize defaultResultSource=_defaultResultSource - In the implementation block
@property (nonatomic,copy) NSUUID * taskRunUUID;                                                 //@synthesize taskRunUUID=_taskRunUUID - In the implementation block
@property (nonatomic,copy,readonly) ORKTaskResult * result; 
@property (nonatomic,copy,readonly) NSData * restorationData; 
@property (nonatomic,copy) NSURL * outputDirectory;                                              //@synthesize outputDirectory=_outputDirectory - In the implementation block
@property (assign,nonatomic) BOOL showsProgressInNavigationBar;                                  //@synthesize showsProgressInNavigationBar=_showsProgressInNavigationBar - In the implementation block
@property (nonatomic,retain) ORKStepViewController * currentStepViewController;                  //@synthesize currentStepViewController=_currentStepViewController - In the implementation block
@property (assign,getter=isNavigationBarHidden,nonatomic) BOOL navigationBarHidden; 
@property (nonatomic,readonly) UINavigationBar * navigationBar; 
@property (assign,nonatomic,__weak) UIScrollView * registeredScrollView;                         //@synthesize registeredScrollView=_registeredScrollView - In the implementation block
@property (nonatomic,retain) UIImageView * hairline;                                             //@synthesize hairline=_hairline - In the implementation block
@property (nonatomic,retain) UINavigationController * childNavigationController;                 //@synthesize childNavigationController=_childNavigationController - In the implementation block
@property (nonatomic,retain) UIPageViewController * pageViewController;                          //@synthesize pageViewController=_pageViewController - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)_pageVc;
+(id)viewControllerWithRestorationIdentifierPath:(id)arg1 coder:(id)arg2 ;
+(void)initialize;
-(void)goBackward;
-(void)stepViewControllerWillAppear:(id)arg1 ;
-(BOOL)stepViewControllerHasPreviousStep:(id)arg1 ;
-(BOOL)stepViewControllerHasNextStep:(id)arg1 ;
-(void)stepViewControllerResultDidChange:(id)arg1 ;
-(void)stepViewController:(id)arg1 didFinishWithNavigationDirection:(long long)arg2 ;
-(void)setOutputDirectory:(NSURL *)arg1 ;
-(NSURL *)outputDirectory;
-(void)_collectToolbarItemsFromViewController:(id)arg1 ;
-(void)_registeredScrollViewDidScroll:(id)arg1 ;
-(void)setChildNavigationController:(UINavigationController *)arg1 ;
-(void)setShowsProgressInNavigationBar:(BOOL)arg1 ;
-(void)setTaskRunUUID:(NSUUID *)arg1 ;
-(UINavigationController *)childNavigationController;
-(id)_findHairlineViewUnder:(id)arg1 ;
-(void)setHairline:(UIImageView *)arg1 ;
-(UIImageView *)hairline;
-(NSUUID *)taskRunUUID;
-(id)_commonInitWithTask:(id)arg1 taskRunUUID:(id)arg2 ;
-(id)initWithTask:(id)arg1 taskRunUUID:(id)arg2 ;
-(long long)desiredPermissions;
-(void)_requestHealthStoreAccessWithReadTypes:(id)arg1 writeTypes:(id)arg2 handler:(/*^block*/id)arg3 ;
-(void)_requestPedometerAccessWithHandler:(/*^block*/id)arg1 ;
-(void)_requestAudioRecordingAccessWithHandler:(/*^block*/id)arg1 ;
-(void)_requestLocationAccessWithHandler:(/*^block*/id)arg1 ;
-(BOOL)_startAudioPromptSessionWithError:(id*)arg1 ;
-(id)_nextStep;
-(BOOL)shouldPresentStep:(id)arg1 ;
-(void)_startAudioPromptSessionIfNeeded;
-(void)_requestHealthAuthorizationWithCompletion:(/*^block*/id)arg1 ;
-(id)_viewControllerForStep:(id)arg1 ;
-(void)_showViewController:(id)arg1 goForward:(BOOL)arg2 animated:(BOOL)arg3 ;
-(ORKStepViewController *)currentStepViewController;
-(void)_setManagedResult:(id)arg1 forKey:(id)arg2 ;
-(id)managedResults;
-(void)_finishAudioPromptSession;
-(void)_updateLastBeginningInstructionStepIdentifierForStep:(id)arg1 goForward:(BOOL)arg2 ;
-(BOOL)_isStepLastBeginningInstructionStep:(id)arg1 ;
-(void)_reportError:(id)arg1 onStep:(id)arg2 ;
-(BOOL)showsProgressInNavigationBar;
-(void)setRegisteredScrollView:(UIScrollView *)arg1 ;
-(id)_defaultCancelButtonItem;
-(id)_defaultLearnMoreButtonItem;
-(void)_finishWithResult:(long long)arg1 error:(id)arg2 ;
-(void)_presentCancelOptions:(BOOL)arg1 ;
-(id)_prevStep;
-(void)_flipToNextPageFrom:(id)arg1 ;
-(void)_flipToPreviousPageFrom:(id)arg1 ;
-(id)_stepBeforeStep:(id)arg1 ;
-(id)_stepAfterStep:(id)arg1 ;
-(void)stepViewControllerDidFail:(id)arg1 withError:(id)arg2 ;
-(id)initWithTask:(id)arg1 restorationData:(id)arg2 ;
-(id)_requestedHealthTypesForRead;
-(id)_requestedHealthTypesForWrite;
-(NSData *)restorationData;
-(id<ORKTaskResultSource>)defaultResultSource;
-(void)setDefaultResultSource:(id<ORKTaskResultSource>)arg1 ;
-(void)setCurrentStepViewController:(ORKStepViewController *)arg1 ;
-(UIScrollView *)registeredScrollView;
-(void)setTask:(id<ORKTask>)arg1 ;
-(void)_cancelAction:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setDelegate:(id<ORKTaskViewControllerDelegate>)arg1 ;
-(id<ORKTaskViewControllerDelegate>)delegate;
-(UINavigationBar *)navigationBar;
-(BOOL)isNavigationBarHidden;
-(void)suspend;
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)decodeRestorableStateWithCoder:(id)arg1 ;
-(void)applicationFinishedRestoringState;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)setNavigationBarHidden:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setNavigationBarHidden:(BOOL)arg1 ;
-(void)resume;
-(void)goForward;
-(ORKTaskResult *)result;
-(id<ORKTask>)task;
-(UIPageViewController *)pageViewController;
-(void)setPageViewController:(UIPageViewController *)arg1 ;
-(void)_learnMoreAction:(id)arg1 ;
@end

