/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UIFont, UIColor, UIView;

@interface ORKTableViewCell : UITableViewCell {

	BOOL _showBottomSeparator;
	BOOL _showTopSeparator;
	UIFont* _labelFont;
	UIColor* _labelTextColor;
	UIColor* _rkSeparatorColor;
	double _topSeparatorLeftInset;
	double _bottomSeparatorLeftInset;
	UIView* _topSeparator;
	UIView* _bottomSeparator;

}

@property (nonatomic,retain) UIFont * labelFont;                           //@synthesize labelFont=_labelFont - In the implementation block
@property (nonatomic,retain) UIColor * labelTextColor;                     //@synthesize labelTextColor=_labelTextColor - In the implementation block
@property (nonatomic,copy) UIColor * rkSeparatorColor;                     //@synthesize rkSeparatorColor=_rkSeparatorColor - In the implementation block
@property (assign,nonatomic) BOOL showBottomSeparator;                     //@synthesize showBottomSeparator=_showBottomSeparator - In the implementation block
@property (assign,nonatomic) BOOL showTopSeparator;                        //@synthesize showTopSeparator=_showTopSeparator - In the implementation block
@property (assign,nonatomic) double topSeparatorLeftInset;                 //@synthesize topSeparatorLeftInset=_topSeparatorLeftInset - In the implementation block
@property (assign,nonatomic) double bottomSeparatorLeftInset;              //@synthesize bottomSeparatorLeftInset=_bottomSeparatorLeftInset - In the implementation block
@property (nonatomic,retain) UIView * topSeparator;                        //@synthesize topSeparator=_topSeparator - In the implementation block
@property (nonatomic,retain) UIView * bottomSeparator;                     //@synthesize bottomSeparator=_bottomSeparator - In the implementation block
-(void)_init_ORKTableViewCell;
-(double)topSeparatorLeftInset;
-(void)setTopSeparatorLeftInset:(double)arg1 ;
-(double)bottomSeparatorLeftInset;
-(void)setBottomSeparatorLeftInset:(double)arg1 ;
-(void)setShowBottomSeparator:(BOOL)arg1 ;
-(void)setShowTopSeparator:(BOOL)arg1 ;
-(UIColor *)rkSeparatorColor;
-(void)setRkSeparatorColor:(UIColor *)arg1 ;
-(BOOL)showBottomSeparator;
-(BOOL)showTopSeparator;
-(void)setLabelFont:(UIFont *)arg1 ;
-(void)setLabelTextColor:(UIColor *)arg1 ;
-(UIColor *)labelTextColor;
-(UIFont *)labelFont;
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)_updateAppearance;
-(void)setTopSeparator:(UIView *)arg1 ;
-(UIView *)topSeparator;
-(void)setBottomSeparator:(UIView *)arg1 ;
-(UIView *)bottomSeparator;
@end

