/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:12 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKRecorder.h>
#import <ResearchKit/ORKTouchRecordingDelegate.h>

@class ORKDataLogger, UIView, ORKTouchGestureRecognizer, NSMutableArray, NSError, NSString;

@interface ORKTouchRecorder : ORKRecorder <ORKTouchRecordingDelegate> {

	ORKDataLogger* _logger;
	UIView* _touchView;
	ORKTouchGestureRecognizer* _gestureRecognizer;
	NSMutableArray* _touchArray;
	double _uptime;
	NSError* _recordingError;

}

@property (nonatomic,readonly) UIView * touchView;                                       //@synthesize touchView=_touchView - In the implementation block
@property (nonatomic,retain) ORKTouchGestureRecognizer * gestureRecognizer;              //@synthesize gestureRecognizer=_gestureRecognizer - In the implementation block
@property (nonatomic,retain) NSMutableArray * touchArray;                                //@synthesize touchArray=_touchArray - In the implementation block
@property (assign,nonatomic) double uptime;                                              //@synthesize uptime=_uptime - In the implementation block
@property (nonatomic,retain) NSError * recordingError;                                   //@synthesize recordingError=_recordingError - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithStep:(id)arg1 outputDirectory:(id)arg2 ;
-(void)finishRecordingWithError:(id)arg1 ;
-(void)setUptime:(double)arg1 ;
-(void)_doStopRecording;
-(id)_recorderType;
-(double)uptime;
-(void)view:(id)arg1 didDetectTouch:(id)arg2 ;
-(UIView *)touchView;
-(void)setTouchArray:(NSMutableArray *)arg1 ;
-(NSMutableArray *)touchArray;
-(void)viewController:(id)arg1 willStartStepWithView:(id)arg2 ;
-(NSError *)recordingError;
-(void)setRecordingError:(NSError *)arg1 ;
-(void)dealloc;
-(void)setGestureRecognizer:(ORKTouchGestureRecognizer *)arg1 ;
-(ORKTouchGestureRecognizer *)gestureRecognizer;
-(void)start;
-(id)mimeType;
-(void)_reset;
-(void)stop;
@end

