/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <UIKit/UIButton.h>
#import <ResearchKit/ORKDefaultFont.h>

@class UIFont, NSString;

@interface ORKTextButton : UIButton <ORKDefaultFont> {

	BOOL _compressFontSize;
	UIFont* _titleFont;

}

@property (nonatomic,retain) UIFont * titleFont;                    //@synthesize titleFont=_titleFont - In the implementation block
@property (assign,nonatomic) BOOL compressFontSize;                 //@synthesize compressFontSize=_compressFontSize - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)buttonWithType:(long long)arg1 ;
+(id)defaultFont;
-(void)_init_ORKTextButton;
-(void)setCompressFontSize:(BOOL)arg1 ;
-(BOOL)compressFontSize;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(id)init;
-(void)tintColorDidChange;
-(CGSize)intrinsicContentSize;
-(id)_defaultFont;
-(UIFont *)titleFont;
-(void)_updateAppearance;
-(void)setTitleFont:(UIFont *)arg1 ;
@end

