/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:16 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class NSString, NSSet;


@protocol ORKTask <NSObject>
@property (nonatomic,copy,readonly) NSString * identifier; 
@property (nonatomic,copy,readonly) NSSet * requestedHealthKitTypesForReading; 
@optional
-(id)stepWithIdentifier:(id)arg1;
-(ORKTaskProgress*)progressOfCurrentStep:(id)arg1 withResult:(id)arg2;
-(NSSet *)requestedHealthKitTypesForReading;

@required
-(id)stepAfterStep:(id)arg1 withResult:(id)arg2;
-(id)stepBeforeStep:(id)arg1 withResult:(id)arg2;
-(NSString *)identifier;

@end

