/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <ResearchKit/ORKAnswerFormat.h>

@interface ORKTextAnswerFormat : ORKAnswerFormat {

	BOOL _multipleLines;
	long long _maximumLength;
	long long _autocapitalizationType;
	long long _autocorrectionType;
	long long _spellCheckingType;

}

@property (readonly) long long maximumLength;                     //@synthesize maximumLength=_maximumLength - In the implementation block
@property (assign) BOOL multipleLines;                            //@synthesize multipleLines=_multipleLines - In the implementation block
@property (assign) long long autocapitalizationType;              //@synthesize autocapitalizationType=_autocapitalizationType - In the implementation block
@property (assign) long long autocorrectionType;                  //@synthesize autocorrectionType=_autocorrectionType - In the implementation block
@property (assign) long long spellCheckingType;                   //@synthesize spellCheckingType=_spellCheckingType - In the implementation block
+(Class)_questionResultClass;
-(id)dictionaryValue;
-(long long)questionType;
-(long long)maximumLength;
-(BOOL)_isAnswerValidWithString:(id)arg1 ;
-(BOOL)multipleLines;
-(void)setMultipleLines:(BOOL)arg1 ;
-(id)initWithMaximumLength:(long long)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(id)initWithDictionary:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(long long)autocapitalizationType;
-(void)setAutocapitalizationType:(long long)arg1 ;
-(long long)autocorrectionType;
-(void)setAutocorrectionType:(long long)arg1 ;
-(long long)spellCheckingType;
-(void)setSpellCheckingType:(long long)arg1 ;
@end

