/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:16 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSValue;

@interface ORKVisualConsentAnimationContext : NSObject {

	BOOL _hasCalledLoadHandler;
	long long _direction;
	/*^block*/id _handler;
	/*^block*/id _loadHandler;
	NSValue* _startTime;
	id _selfRef;

}

@property (assign,nonatomic) long long direction;                    //@synthesize direction=_direction - In the implementation block
@property (assign,nonatomic) BOOL hasCalledLoadHandler;              //@synthesize hasCalledLoadHandler=_hasCalledLoadHandler - In the implementation block
@property (nonatomic,copy) id handler;                               //@synthesize handler=_handler - In the implementation block
@property (nonatomic,copy) id loadHandler;                           //@synthesize loadHandler=_loadHandler - In the implementation block
@property (nonatomic,retain) NSValue * startTime;                    //@synthesize startTime=_startTime - In the implementation block
@property (nonatomic,retain) id selfRef;                             //@synthesize selfRef=_selfRef - In the implementation block
-(BOOL)hasCalledLoadHandler;
-(void)setHasCalledLoadHandler:(BOOL)arg1 ;
-(id)selfRef;
-(void)setSelfRef:(id)arg1 ;
-(void)setStartTime:(NSValue *)arg1 ;
-(void)setDirection:(long long)arg1 ;
-(long long)direction;
-(void)setHandler:(id)arg1 ;
-(id)handler;
-(NSValue *)startTime;
-(void)setLoadHandler:(id)arg1 ;
-(id)loadHandler;
@end

