/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:16 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/AVPlayerItemOutputPullDelegate.h>

@protocol OS_dispatch_queue;
@class ORKVisualConsentStepViewController, NSURL, AVPlayer, AVPlayerItem, CADisplayLink, AVPlayerItemVideoOutput, NSObject, ORKVisualConsentAnimationContext, NSString;

@interface ORKVisualConsentTransitionAnimator : NSObject <AVPlayerItemOutputPullDelegate> {

	ORKVisualConsentStepViewController* _stepViewController;
	NSURL* _movieURL;
	AVPlayer* _moviePlayer;
	AVPlayerItem* _playerItem;
	BOOL _observingPlayerDurationKey;
	BOOL _observingPlayerItemStatusKey;
	CADisplayLink* _displayLink;
	AVPlayerItemVideoOutput* _videoOutput;
	NSObject*<OS_dispatch_queue> _videoOutputQueue;
	long long _frameCounter;
	ORKVisualConsentAnimationContext* _pendingContext;

}

@property (nonatomic,copy,readonly) NSURL * movieURL; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithVisualConsentStepViewController:(id)arg1 movieURL:(id)arg2 ;
-(void)animateTransitionWithDirection:(long long)arg1 withLoadHandler:(/*^block*/id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)displayLinkCallback:(id)arg1 ;
-(void)_attemptAnimationWithContext:(id)arg1 ;
-(void)_performAnimationWithContext:(id)arg1 ;
-(void)_finishAnimationWithContext:(id)arg1 ;
-(void)playbackDidFinish:(id)arg1 ;
-(void)_initialFrameDidDisplay;
-(NSURL *)movieURL;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)finish;
-(void)outputMediaDataWillChange:(id)arg1 ;
@end

