/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ORKStepViewController.h>
#import <UIKit/UIPageViewControllerDelegate.h>

@class ORKVisualConsentTransitionAnimator, NSArray, UIView, UIPageViewController, NSMutableDictionary, UIScrollView, ORKContinueButton, NSString;

@interface ORKVisualConsentStepViewController : ORKStepViewController <UIPageViewControllerDelegate> {

	BOOL _hasAppeared;
	long long _navDirection;
	BOOL _transitioning;
	ORKVisualConsentTransitionAnimator* _animator;
	NSArray* _visualSections;
	UIView* _animationView;
	UIPageViewController* _pageViewController;
	NSMutableDictionary* _viewControllers;
	UIScrollView* _scrollView;
	unsigned long long _currentPage;
	ORKContinueButton* _continueActionButton;

}

@property (nonatomic,retain) UIView * animationView;                                 //@synthesize animationView=_animationView - In the implementation block
@property (nonatomic,retain) UIPageViewController * pageViewController;              //@synthesize pageViewController=_pageViewController - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * viewControllers;                  //@synthesize viewControllers=_viewControllers - In the implementation block
@property (nonatomic,retain) UIScrollView * scrollView;                              //@synthesize scrollView=_scrollView - In the implementation block
@property (assign,nonatomic) unsigned long long currentPage;                         //@synthesize currentPage=_currentPage - In the implementation block
@property (nonatomic,retain) ORKContinueButton * continueActionButton;               //@synthesize continueActionButton=_continueActionButton - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_stepDidChange;
-(void)_setBackButtonItem:(id)arg1 ;
-(void)_updateNavLeftBarButtonItem;
-(void)_willNavigateDirection:(long long)arg1 ;
-(id)visualConsentStep;
-(id)_viewControllerForIndex:(unsigned long long)arg1 ;
-(void)_showViewController:(id)arg1 forward:(BOOL)arg2 animated:(BOOL)arg3 ;
-(void)setAnimationView:(UIView *)arg1 ;
-(void)_updatePageIndex;
-(void)_updateBackButton;
-(void)_goToPreviousPage;
-(unsigned long long)_currentIndex;
-(id)_goToPreviousPageButton;
-(id)_findHairlineImageViewUnder:(id)arg1 ;
-(void)_doShowViewController:(id)arg1 direction:(long long)arg2 animated:(BOOL)arg3 semaphore:(id)arg4 ;
-(void)_finishTransitioningAnimator:(id)arg1 ;
-(id)animationPlayerView;
-(unsigned long long)_indexOfViewController:(id)arg1 ;
-(id)_doAnimateFromViewController:(id)arg1 toController:(id)arg2 direction:(long long)arg3 semaphore:(id)arg4 url:(id)arg5 animateBeforeTransition:(BOOL)arg6 transitionBeforeAnimate:(BOOL)arg7 ;
-(id)_visualSections;
-(void)_next;
-(ORKContinueButton *)continueActionButton;
-(void)setContinueActionButton:(ORKContinueButton *)arg1 ;
-(void)_setScrollEnabled:(BOOL)arg1 ;
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)decodeRestorableStateWithCoder:(id)arg1 ;
-(void)setScrollView:(UIScrollView *)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(NSMutableDictionary *)viewControllers;
-(UIScrollView *)scrollView;
-(void)setViewControllers:(NSMutableDictionary *)arg1 ;
-(unsigned long long)_pageCount;
-(void)setCurrentPage:(unsigned long long)arg1 ;
-(unsigned long long)currentPage;
-(void)pageViewController:(id)arg1 didFinishAnimating:(BOOL)arg2 previousViewControllers:(id)arg3 transitionCompleted:(BOOL)arg4 ;
-(id)pageViewController:(id)arg1 viewControllerBeforeViewController:(id)arg2 ;
-(id)pageViewController:(id)arg1 viewControllerAfterViewController:(id)arg2 ;
-(UIPageViewController *)pageViewController;
-(void)setPageViewController:(UIPageViewController *)arg1 ;
-(UIView *)animationView;
@end

