/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:15 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ResearchKit/ResearchKit-Structs.h>
#import <UIKit/UIScrollView.h>

@class UIView, NSDictionary, NSLayoutConstraint, NSArray, UIImageView, ORKStepHeaderView, ORKContinueSkipContainerView;

@interface ORKVerticalContainerView : UIScrollView {

	UIView* _scrollContainer;
	UIView* _container;
	NSDictionary* _adjustableConstraints;
	NSLayoutConstraint* _continueAtBottomConstraint;
	NSLayoutConstraint* _continueInContentConstraint;
	double _keyboardOverlap;
	UIView* _stepViewContainer;
	BOOL _keyboardIsUp;
	NSArray* _customViewContainerConstraints;
	BOOL _continueHugsContent;
	BOOL _verticalCenteringEnabled;
	BOOL _stepViewFillsAvailableSpace;
	UIImageView* _imageView;
	UIView* _customViewContainer;
	UIView* _stepView;
	UIView* _customView;
	ORKStepHeaderView* _headerView;
	ORKContinueSkipContainerView* _continueSkipContainer;
	double _minimumStepHeaderHeight;
	long long _screenType;

}

@property (nonatomic,retain) UIImageView * imageView;                                           //@synthesize imageView=_imageView - In the implementation block
@property (nonatomic,retain) UIView * customViewContainer;                                      //@synthesize customViewContainer=_customViewContainer - In the implementation block
@property (nonatomic,retain) UIView * stepView;                                                 //@synthesize stepView=_stepView - In the implementation block
@property (nonatomic,retain) UIView * customView;                                               //@synthesize customView=_customView - In the implementation block
@property (nonatomic,retain) ORKStepHeaderView * headerView;                                    //@synthesize headerView=_headerView - In the implementation block
@property (nonatomic,retain) ORKContinueSkipContainerView * continueSkipContainer;              //@synthesize continueSkipContainer=_continueSkipContainer - In the implementation block
@property (assign,nonatomic) BOOL continueHugsContent;                                          //@synthesize continueHugsContent=_continueHugsContent - In the implementation block
@property (assign,nonatomic) BOOL verticalCenteringEnabled;                                     //@synthesize verticalCenteringEnabled=_verticalCenteringEnabled - In the implementation block
@property (assign,nonatomic) BOOL stepViewFillsAvailableSpace;                                  //@synthesize stepViewFillsAvailableSpace=_stepViewFillsAvailableSpace - In the implementation block
@property (assign,nonatomic) double minimumStepHeaderHeight;                                    //@synthesize minimumStepHeaderHeight=_minimumStepHeaderHeight - In the implementation block
@property (nonatomic,readonly) long long screenType;                                            //@synthesize screenType=_screenType - In the implementation block
-(void)setStepViewFillsAvailableSpace:(BOOL)arg1 ;
-(void)setStepView:(UIView *)arg1 ;
-(ORKContinueSkipContainerView *)continueSkipContainer;
-(void)_tapOffAction:(id)arg1 ;
-(void)_updateContinueButtonConstraints;
-(void)_registerForKeyboardNotifications:(BOOL)arg1 ;
-(void)keyboardFrameWillChange:(id)arg1 ;
-(CGSize)_keyboardIntersectionSizeFromNotification:(id)arg1 ;
-(void)_updateToInsets:(UIEdgeInsets)arg1 ;
-(void)_animateLayoutForKeyboardNotification:(id)arg1 ;
-(void)setMinimumStepHeaderHeight:(double)arg1 ;
-(void)setVerticalCenteringEnabled:(BOOL)arg1 ;
-(void)setContinueHugsContent:(BOOL)arg1 ;
-(void)_updateConstraintConstants;
-(UIView *)customViewContainer;
-(UIView *)stepView;
-(void)_swipeOffAction:(id)arg1 ;
-(BOOL)continueHugsContent;
-(BOOL)stepViewFillsAvailableSpace;
-(void)_updateCustomViewContainerConstraints;
-(void)_updateStepViewContainerConstraints;
-(void)setCustomViewContainer:(UIView *)arg1 ;
-(void)setContinueSkipContainer:(ORKContinueSkipContainerView *)arg1 ;
-(BOOL)verticalCenteringEnabled;
-(double)minimumStepHeaderHeight;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)willMoveToWindow:(id)arg1 ;
-(void)updateConstraints;
-(UIImageView *)imageView;
-(UIView *)customView;
-(ORKStepHeaderView *)headerView;
-(void)setHeaderView:(ORKStepHeaderView *)arg1 ;
-(long long)screenType;
-(void)setCustomView:(UIView *)arg1 ;
-(void)setImageView:(UIImageView *)arg1 ;
-(void)keyboardWillShow:(id)arg1 ;
-(void)keyboardWillHide:(id)arg1 ;
@end

