#import <ResearchKit/_ORKFitnessStepViewController.h>
#import <ResearchKit/ORKVisualConsentStep.h>
#import <ResearchKit/ORKLocationRecorder.h>
#import <ResearchKit/ORKLocationRecorderConfiguration.h>
#import <ResearchKit/ORKTouchGestureRecognizer.h>
#import <ResearchKit/ORKTouchRecorder.h>
#import <ResearchKit/ORKTouchRecorderConfiguration.h>
#import <ResearchKit/ORKTapCountLabel.h>
#import <ResearchKit/ORKLabel.h>
#import <ResearchKit/ORKDeviceMotionRecorder.h>
#import <ResearchKit/ORKDeviceMotionRecorderConfiguration.h>
#import <ResearchKit/ORKStepViewController.h>
#import <ResearchKit/_ORKConsentSignatureWrapperView.h>
#import <ResearchKit/ORKConsentSigningView.h>
#import <ResearchKit/_ORKConsentSignatureController.h>
#import <ResearchKit/ORKFormStep.h>
#import <ResearchKit/ORKFormItem.h>
#import <ResearchKit/_ORKTableContainerView.h>
#import <ResearchKit/_ORKSpatialSpanGame.h>
#import <ResearchKit/_ORKState.h>
#import <ResearchKit/_ORKSpatialSpanMemoryStepViewController.h>
#import <ResearchKit/_ORKCaretOptionalTextField.h>
#import <ResearchKit/_ORKUnitTextField.h>
#import <ResearchKit/_ORKTextFieldView.h>
#import <ResearchKit/ORKSelectionSubTitleLabel.h>
#import <ResearchKit/_ORKLocationAuthorizationRequester.h>
#import <ResearchKit/_ORKObserver.h>
#import <ResearchKit/_ORKTaskViewControllerObserver.h>
#import <ResearchKit/_ORKScrollViewObserver.h>
#import <ResearchKit/ORKTaskViewController.h>
#import <ResearchKit/ORKConsentLearnMoreViewController.h>
#import <ResearchKit/ORKScaleSlider.h>
#import <ResearchKit/ORKActiveStep.h>
#import <ResearchKit/ORKRoundTappingButton.h>
#import <ResearchKit/ORKSignatureGestureRecognizer.h>
#import <ResearchKit/ORKSignatureView.h>
#import <ResearchKit/ORKVoiceEngine.h>
#import <ResearchKit/_ORKSegmentedControl.h>
#import <ResearchKit/_ORKFormItemCell.h>
#import <ResearchKit/_ORKFormItemTextFieldBasedCell.h>
#import <ResearchKit/_ORKFormItemTimeOfDayCell.h>
#import <ResearchKit/_ORKFormItemDateCell.h>
#import <ResearchKit/_ORKFormItemTextFieldCell.h>
#import <ResearchKit/_ORKFormItemNumericCell.h>
#import <ResearchKit/_ORKFormItemTextCell.h>
#import <ResearchKit/_ORKFormItemTimeIntervalCell.h>
#import <ResearchKit/_ORKFormItemImageSelectionCell.h>
#import <ResearchKit/_ORKFormItemValuePickerCell.h>
#import <ResearchKit/ORKSurveyAnswerCellForText.h>
#import <ResearchKit/ORKSurveyAnswerCellForTextField.h>
#import <ResearchKit/ORKAnswerTextView.h>
#import <ResearchKit/ORKImageChoiceLabel.h>
#import <ResearchKit/ORKConsentReviewStep.h>
#import <ResearchKit/ORKFormSectionTitleLabel.h>
#import <ResearchKit/ORKSurveyAnswerCell.h>
#import <ResearchKit/ORKBorderedButton.h>
#import <ResearchKit/ORKConsentSignature.h>
#import <ResearchKit/_ORKWalkingProgressCircleView.h>
#import <ResearchKit/_ORKWalkingProgressView.h>
#import <ResearchKit/_ORKWalkingContentView.h>
#import <ResearchKit/_ORKWalkingTaskStepViewController.h>
#import <ResearchKit/ORKAnimationPlaceholderView.h>
#import <ResearchKit/ORKVisualConsentStepViewController.h>
#import <ResearchKit/ORKMediaStep.h>
#import <ResearchKit/ORKHtmlPdfPageRenderer.h>
#import <ResearchKit/ORKHtmlPdfWriter.h>
#import <ResearchKit/ORKHealthKitCharacteristicTypeAnswerFormat.h>
#import <ResearchKit/ORKHealthKitQuantityTypeAnswerFormat.h>
#import <ResearchKit/ORKSelectionTitleLabel.h>
#import <ResearchKit/ORKChoiceViewCell.h>
#import <ResearchKit/_ORKPathView.h>
#import <ResearchKit/_ORKSpatialSpanTargetView.h>
#import <ResearchKit/ORKSubheadlineLabel.h>
#import <ResearchKit/_ORKSpatialSpanMemoryGameView.h>
#import <ResearchKit/_ORKSpatialSpanMemoryContentView.h>
#import <ResearchKit/ORKInstructionStep.h>
#import <ResearchKit/_ORKFitnessContentView.h>
#import <ResearchKit/ORKConsentSection.h>
#import <ResearchKit/_ORKCountdownStep.h>
#import <ResearchKit/ORKHealthQuantityTypeRecorder.h>
#import <ResearchKit/ORKHealthQuantityTypeRecorderConfiguration.h>
#import <ResearchKit/ORKTableViewCell.h>
#import <ResearchKit/ORKScaleValueLabel.h>
#import <ResearchKit/ORKStep.h>
#import <ResearchKit/ORKHeadlineLabel.h>
#import <ResearchKit/ORKCaption1Label.h>
#import <ResearchKit/ORKConsentDocument.h>
#import <ResearchKit/_ORKTintedImageView.h>
#import <ResearchKit/_ORKQuantityLabel.h>
#import <ResearchKit/_ORKActiveStepQuantityView.h>
#import <ResearchKit/_ORKQuantityPairView.h>
#import <ResearchKit/_ORKTableCellItem.h>
#import <ResearchKit/_ORKTableSection.h>
#import <ResearchKit/ORKFormStepViewController.h>
#import <ResearchKit/ORKSurveyAnswerCellForTimeInterval.h>
#import <ResearchKit/ORKActiveStepTimerView.h>
#import <ResearchKit/_ORKAudioStepViewController.h>
#import <ResearchKit/ORKCountdownLabel.h>
#import <ResearchKit/ORKConsentSceneView.h>
#import <ResearchKit/ORKConsentSceneViewController.h>
#import <ResearchKit/ORKRecorderConfiguration.h>
#import <ResearchKit/ORKRecorder.h>
#import <ResearchKit/ORKSurveyAnswerCellForNumber.h>
#import <ResearchKit/_ORKTappingIntervalStep.h>
#import <ResearchKit/ORKResult.h>
#import <ResearchKit/ORKTappingSample.h>
#import <ResearchKit/ORKSpatialSpanMemoryGameTouchSample.h>
#import <ResearchKit/ORKSpatialSpanMemoryGameRecord.h>
#import <ResearchKit/ORKSpatialSpanMemoryResult.h>
#import <ResearchKit/ORKTappingIntervalResult.h>
#import <ResearchKit/ORKFileResult.h>
#import <ResearchKit/ORKDataResult.h>
#import <ResearchKit/ORKConsentSignatureResult.h>
#import <ResearchKit/ORKQuestionResult.h>
#import <ResearchKit/ORKScaleQuestionResult.h>
#import <ResearchKit/ORKChoiceQuestionResult.h>
#import <ResearchKit/ORKBooleanQuestionResult.h>
#import <ResearchKit/ORKTextQuestionResult.h>
#import <ResearchKit/ORKNumericQuestionResult.h>
#import <ResearchKit/ORKTimeOfDayQuestionResult.h>
#import <ResearchKit/ORKTimeIntervalQuestionResult.h>
#import <ResearchKit/ORKDateQuestionResult.h>
#import <ResearchKit/ORKCollectionResult.h>
#import <ResearchKit/ORKTaskResult.h>
#import <ResearchKit/ORKStepResult.h>
#import <ResearchKit/_ORKInstructionStepView.h>
#import <ResearchKit/ORKSurveyAnswerCellForScale.h>
#import <ResearchKit/_ORKCountDownViewLabel.h>
#import <ResearchKit/_ORKCountdownView.h>
#import <ResearchKit/_ORKCountdownStepViewController.h>
#import <ResearchKit/ORKContinueButton.h>
#import <ResearchKit/ORKPedometerRecorder.h>
#import <ResearchKit/ORKPedometerRecorderConfiguration.h>
#import <ResearchKit/ORKScaleRangeLabel.h>
#import <ResearchKit/_ORKWalkingTaskStep.h>
#import <ResearchKit/_ORKSpatialSpanGameState.h>
#import <ResearchKit/ORKBodyLabel.h>
#import <ResearchKit/ORKAudioRecorder.h>
#import <ResearchKit/ORKAudioRecorderConfiguration.h>
#import <ResearchKit/_ORKTappingIntervalStepViewController.h>
#import <ResearchKit/ORKConsentReviewStepViewController.h>
#import <ResearchKit/ORKEAGLMoviePlayerView.h>
#import <ResearchKit/ORKCompletionStep.h>
#import <ResearchKit/_ORKFitnessStep.h>
#import <ResearchKit/_ORKTappingContentView.h>
#import <ResearchKit/ORKAnswerTextField.h>
#import <ResearchKit/_ORKSpatialSpanMemoryStep.h>
#import <ResearchKit/ORKUnitLabel.h>
#import <ResearchKit/_ORKAudioGraphView.h>
#import <ResearchKit/_ORKAudioTimerLabel.h>
#import <ResearchKit/_ORKAudioContentView.h>
#import <ResearchKit/ORKActiveStepViewController.h>
#import <ResearchKit/ORKAnswerDefaultSource.h>
#import <ResearchKit/ORKAnswerFormat.h>
#import <ResearchKit/ORKValuePickerAnswerFormat.h>
#import <ResearchKit/ORKImageChoiceAnswerFormat.h>
#import <ResearchKit/ORKTextChoiceAnswerFormat.h>
#import <ResearchKit/ORKTextChoice.h>
#import <ResearchKit/ORKImageChoice.h>
#import <ResearchKit/ORKBooleanAnswerFormat.h>
#import <ResearchKit/ORKTimeOfDayAnswerFormat.h>
#import <ResearchKit/ORKDateAnswerFormat.h>
#import <ResearchKit/ORKNumericAnswerFormat.h>
#import <ResearchKit/ORKScaleAnswerFormat.h>
#import <ResearchKit/ORKContinuousScaleAnswerFormat.h>
#import <ResearchKit/ORKTextAnswerFormat.h>
#import <ResearchKit/ORKTimeIntervalAnswerFormat.h>
#import <ResearchKit/ORKConsentSharingStepViewController.h>
#import <ResearchKit/ORKSurveyAnswerCellForImageSelection.h>
#import <ResearchKit/_ORKChoiceButtonView.h>
#import <ResearchKit/_ORKImageSelectionView.h>
#import <ResearchKit/ORKInstructionStepViewController.h>
#import <ResearchKit/ORKAccelerometerRecorder.h>
#import <ResearchKit/ORKAccelerometerRecorderConfiguration.h>
#import <ResearchKit/ORKActiveStepTimer.h>
#import <ResearchKit/ORKConsentSharingStep.h>
#import <ResearchKit/ORKSurveyAnswerCellForDateTime.h>
#import <ResearchKit/ORKVerticalContainerView.h>
#import <ResearchKit/ORKActiveStepView.h>
#import <ResearchKit/ORKContinueSkipContainerView.h>
#import <ResearchKit/ORKStepHeaderView.h>
#import <ResearchKit/ORKQuestionStepView.h>
#import <ResearchKit/ORKQuestionStepCellHolderView.h>
#import <ResearchKit/ORKMediaOverlayView.h>
#import <ResearchKit/ORKMediaStepViewController.h>
#import <ResearchKit/ORKCompletionStepView.h>
#import <ResearchKit/ORKCompletionStepViewController.h>
#import <ResearchKit/ORKQuestionStepViewController.h>
#import <ResearchKit/_ORKConsentReviewController.h>
#import <ResearchKit/ORKFormTextView.h>
#import <ResearchKit/ORKTextButton.h>
#import <ResearchKit/_ORKObjectObserver.h>
#import <ResearchKit/ORKLogFormatter.h>
#import <ResearchKit/ORKJSONLogFormatter.h>
#import <ResearchKit/ORKDataLogger.h>
#import <ResearchKit/ORKDataLoggerManager.h>
#import <ResearchKit/ORKActiveStepCustomView.h>
#import <ResearchKit/ORKQuestionStepCustomView.h>
#import <ResearchKit/_ORKAudioStep.h>
#import <ResearchKit/ORKOrderedTask.h>
#import <ResearchKit/ORKQuestionStep.h>
#import <ResearchKit/ORKSurveyAnswerCellForSingleSelectionPicker.h>
#import <ResearchKit/ORKVisualConsentAnimationContext.h>
#import <ResearchKit/ORKVisualConsentTransitionAnimator.h>
