/*
* This header is generated by classdump-dyld 0.7
* on Monday, March 9, 2015 at 8:56:13 PM Greenwich Mean Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /private/var/mobile/Containers/Bundle/Application/59532D3A-E75D-48D6-95BE-6EFEA922624C/Parkinson.app/Frameworks/ResearchKit.framework/ResearchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UIPageViewControllerDelegate <NSObject>
@optional
-(void)pageViewController:(id)arg1 willTransitionToViewControllers:(id)arg2;
-(void)pageViewController:(id)arg1 didFinishAnimating:(BOOL)arg2 previousViewControllers:(id)arg3 transitionCompleted:(BOOL)arg4;
-(long long)pageViewController:(id)arg1 spineLocationForInterfaceOrientation:(long long)arg2;
-(unsigned long long)pageViewControllerSupportedInterfaceOrientations:(id)arg1;
-(long long)pageViewControllerPreferredInterfaceOrientationForPresentation:(id)arg1;

@end

